### ISSUE TITLE
LiteralsExtractor buggy

### ISSUE THREAD

**Issue by SoltauFintel** [jxlsteam/jxls#111]
Pre-release test 2.10.0-rc2 failed.

"//jx:if(...)" becomes "jx:if(...)" because of a bug in LiteralsExtractor.

**Comment by SoltauFintel** [comment]
hi @alexlust
please have a look in bug #111 . Can you fix it soon or shall we revert your feature to give you more time to stabilize the feature?

Please respond in #111

Your changes should be based on branch feature-111 (please see #112)

**Comment by alexlust** [comment]
Hi, I will look at the bug and fix it.
I hope that today or tomorrow I fixed the bug.

**Comment by SoltauFintel** [comment]
Would be good if your algorithm could also handle other disturbing things; example:

<pre>// comment
[whitespace] jx:if  [whitespace] (  name="value"
[whitespace]  name="value"  [whitespace]
[whitespace] ) [whitespace]
[empty line]
// comment
[empty line]
[whitespace] jx:each  [whitespace] (  items=...
</pre>

**Comment by alexlust** [comment]
Unfortunately it took me longer to start. I'm on it.

**Comment by alexlust** [comment]
I fixed the bug and tested it with the constellation listed above.

**Comment by SoltauFintel** [comment]
This feature must be activated before use:

`XlsCommentAreaBuilder.MULTI_LINE_SQL_FEATURE = true;`
