### ISSUE TITLE
Jxls memory usage

### ISSUE THREAD

**Issue by shrimp9469** [jxlsteam/jxls#115]
Hello, 
       I used the .xlsx template to export about 55 columns of nearly 60,000 rows of data. I found that the memory usage reached about 7G, and it was not automatically released for a period of time after normal export. 
      Excuse me, is the memory footprint normal? Is there a way to solve the memory footprint and release problems?

_Originally posted by @shrimp9469 in https://github.com/jxlsteam/jxls/discussions/114_

**Comment by SoltauFintel** [comment]
crosspost and duplicate to #59
