### ISSUE TITLE
How to set the column width auto

### ISSUE THREAD

**Issue by firstmetcs** [jxlsteam/jxls#122]
How can I set the column width been adjusted Automatically

**Comment by firstmetcs** [comment]
sheet.autoSizeColumn(i);

**Comment by SoltauFintel** [comment]
- Have you searched on e.g. StackOverflow?
- Have you tried the GridCommand?
- Please use Github Discussions for questions.

**Comment by SoltauFintel** [comment]
lol, the solution is already on Discussions
