### ISSUE TITLE
Contribute jxls1 support for POI4

### ISSUE THREAD

**Issue by edu-de** [jxlsteam/jxls#125]
Hi,

as we currently use jxls1 adapted in order to support POI4, we would like to contribute with our code. As this is not jxls2 code (available here in GitHub), I would like to ask how to send you the code or where to make a pull request or similar?
The code we use is available here: https://github.com/infofabrik/reportserver/tree/main/jxls-src
but we would of course prefer to delete this code and use an official package. I understand jxls1 is not further developed, but maybe it is possible to release the adapted jxls1 code?

The changes to jxls1 are minor changes, these I describe here: https://stackoverflow.com/questions/66989629/compatibility-between-apache-poi-4-1-2-and-net-sf-jxls-jxls-core-1-0-6

**Comment by edu-de** [comment]
Two JUnit tests did not pass: net.sf.jxls.ForEachTest.testForOneRowMerge() and net.sf.jxls.ForEachTest.testForOneRowMerge2(), both had similar stacktraces:

Cannot add merged region A1:B1 to sheet because it overlaps with an existing merged region (B1:C1).

We will look into this

**Comment by edu-de** [comment]
There was a small bug while merging in the jxls1 code, but I fixed that. There was also a small issue with poiobjects.xls together with POI 4 (method was deprecated and was removed) which is also solved. So now all jxls-core JUnit tests pass correctly.

How should I send you the code ?

**Comment by leonate** [comment]
Jxls-1 source code previously was kept at Sourceforge.
I will check if I can revive it and push to a repo on Github so that you can contribute.

**Comment by leonate** [comment]
@edu-de I imported the Jxls-1.x source code to https://github.com/jxlsteam/jxls-1-legacy so you may contribute.

**Comment by edu-de** [comment]
@leonate thanks for the repo. I created a pull-request: https://github.com/jxlsteam/jxls-1-legacy/pull/1
