### ISSUE TITLE
multiple formulas only resolved once

### ISSUE THREAD

**Issue by giufus** [jxlsteam/jxls#126]
Hi, 

Using last version of jxls in a project 

- 'org.jxls:jxls:2.10.0'
- 'org.jxls:jxls-poi:2.10.0'

In a "each" row, last 2 columns contain formulas (something like sum of some previous columns of the row):

$[SUM(G14+J14+M14+P14+S14)]  
$[SUM(H14+K14+N14+Q14+T14)]

Only the first is propagated with increment in the generated rows, the second's formula column always shows n copy of 
=SUM(H14+K14+N14+Q14+T14)

Entering debug I see this behaviour:
![image](https://user-images.githubusercontent.com/1756470/116685041-0bab9880-a9b2-11eb-86a4-489e1f598802.png)

The 2nd iteration targetCellDataList is empty and going deeper 
![image](https://user-images.githubusercontent.com/1756470/116685426-9db3a100-a9b2-11eb-87c5-74ab7ee51dd2.png)

seems we are requesting the N element of cellDataList but the N position of the List is null.

This is a piece of code I'm running:

`
Transformer transformer = TransformerFactory.createTransformer(is, os);

transformer.setEvaluateFormulas(true);

AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
List<Area> xlsAreaList = areaBuilder.build();
Area xlsArea = xlsAreaList.get(0);

JexlExpressionEvaluator evaluator = (JexlExpressionEvaluator) transformer.getTransformationConfig().getExpressionEvaluator();
Map<String, Object> functionMap = new HashMap<>();
functionMap.put("demo", new MyCustomFunctions());
JexlEngine customJexlEngine = new JexlBuilder().namespaces(functionMap).create();
evaluator.setJexlEngine(customJexlEngine);
xlsArea.applyAt(new CellRef("MY_SHEET!A1"), context);
xlsArea.processFormulas();
transformer.resetTargetCellRefs();
transformer.write();
`
Any suggestion ?

**Comment by SoltauFintel** [comment]
Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.

**Comment by SoltauFintel** [comment]
Please submit a PR with a working testcase. The testcase should contain assertions. You can find many testcase examples in our repository, e.g. IssueB198Test.

https://github.com/jxlsteam/jxls/blob/master/CONTRIBUTING.md
