### ISSUE TITLE
GroupSum with condition

### ISSUE THREAD

**Issue by Deninc** [jxlsteam/jxls#129]
I know that we already have:
```
${G.sum("salary", d.items)}
```

It would be great if we can have:
```
${G.sum("salary", d.items, "department=IT")}
```

This is equivalent to general SQL:
```
sum(case when department = 'IT' then salary else 0 end)
```

or Postgres:
```
sum(salary) filter where (department = 'IT')
```

Or is there other way to achive this?

**Comment by SoltauFintel** [comment]
This would be an enhancement.

JXLS class GroupSum must be extended. Condition can be checked like IfCommand does it: `Boolean conditionResult = Util.isConditionTrue(getTransformationConfig().getExpressionEvaluator(), condition, context);`

**Comment by SoltauFintel** [comment]
With the _current_ JXLS version 2.10 you can do something like this:

write a filter function for the list

`${G.sum("salary", MYCLASS.filterITDepartments(d.items))}`

Add a Java class to the JXLS context with key "MYCLASS" (or other key). Input+Output: Collection
