### ISSUE TITLE
jx:area lastCell cause cell merge useless

### ISSUE THREAD

**Issue by imic07** [jxlsteam/jxls#130]
when jx:area not contains all template (jx:area(lastCell = "E5")), the output's merged cell will unmerge!

**template:**
![image](https://user-images.githubusercontent.com/16321067/120501813-7e19f900-c3f4-11eb-963c-6686f22909dc.png)

**jxls version**
```
<dependency>
      <groupId>org.jxls</groupId>
      <artifactId>jxls-poi</artifactId>
      <version>2.10.0</version>
  </dependency>
  <dependency>
      <groupId>org.jxls</groupId>
      <artifactId>jxls</artifactId>
      <version>2.10.0</version>
  </dependency>
```

**output:**
![image](https://user-images.githubusercontent.com/16321067/120501901-912cc900-c3f4-11eb-9edb-0b273cb7218f.png)

**when i change the jx:area to**   
```
jx:area(lastCell = "E9")
```

**the output is ok:**
![image](https://user-images.githubusercontent.com/16321067/120502826-54ad9d00-c3f5-11eb-86da-830f02b6bfbd.png)

**Comment by SoltauFintel** [comment]
Please submit a Pull Request with a testcase. Please add also the expected XLSX file. It would be nice if the Excel file does not contain Chinese letters.

https://github.com/jxlsteam/jxls/blob/master/CONTRIBUTING.md
