### ISSUE TITLE
Using multisheet cause the hidden row or column becomes visible?

### ISSUE THREAD

**Issue by liaoxuewei** [jxlsteam/jxls#133]
If you do not use multisheet, hidden rows or columns can be hidden normally, but after using multisheet, the hidden row or column becomes visible. Is there any solution?

**Comment by liaoxuewei** [comment]
I found and modified a custom hidden command to fix the to solve this problem temporarily, but I think Jxls should be caused by some problems.
`
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.jxls.area.Area;
import org.jxls.builder.xls.XlsCommentAreaBuilder;
import org.jxls.command.AbstractCommand;
import org.jxls.command.Command;
import org.jxls.common.CellRef;
import org.jxls.common.Context;
import org.jxls.common.Size;
import org.jxls.transform.poi.PoiTransformer;
import org.jxls.util.Util;

public class HiddenCommand extends AbstractCommand {
    public static final String COMMAND_NAME = "hidden";

    public static final String ROW = "row";
    public static final String COL = "col";

    /**
     * 隐藏行还是列  行：row， 列：col
     */
    private String hidTag;
    /**
     * 条件
     */
    private String condition;
    private Area area;

    @Override
    public String getName() {
        return COMMAND_NAME;
    }

    @Override
    public Command addArea(Area area) {
        if (super.getAreaList().size() >= 1) {
            throw new IllegalArgumentException("You can add only a single area to 'merge' command");
        }
        this.area = area;
        return super.addArea(area);
    }

    @Override
    public Size applyAt(CellRef cellRef, Context context) {
        Boolean conditionResult = condition == null || "".equals(condition)
                || Util.isConditionTrue(getTransformationConfig().getExpressionEvaluator(), condition, context);
        if (conditionResult.booleanValue()) {
            PoiTransformer transformer = (PoiTransformer) this.getTransformer();
            Sheet sheet = transformer.getWorkbook().getSheet(cellRef.getSheetName());

            CellRef srcCell = area.getStartCellRef();
            if (ROW.equals(hidTag)) {
                int rowNub = srcCell.getRow();
                for (int i = 0; i < area.getSize().getHeight(); i++) {
                    Row row = sheet.getRow(rowNub + i);
                    short rowHeight = 0;
                    row.setHeight(rowHeight);
                }
            }
            if (COL.equals(hidTag)) {
                int col = srcCell.getCol();
                for (int i = 0; i < area.getSize().getWidth(); i++) {
                    sheet.setColumnHidden(col + i, true);
                }
            }
        }
        return area.applyAt(cellRef, context);
    }

    public String getHidTag() {
        return hidTag;
    }

    public void setHidTag(String hidTag) {
        this.hidTag = hidTag;
    }

    public static String getCommandName() {
        return COMMAND_NAME;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public static void nop() {
        //call this function to init
    }

    static {
        XlsCommentAreaBuilder.addCommandMapping(HiddenCommand.COMMAND_NAME, HiddenCommand.class);
    }
}
`

**Comment by SoltauFintel** [comment]
I think this has not the quality to transfer it to JXLS master. But it can be a inspiration for other jxls users. However, I want to close this ticket in near future.

@leonate  What shall we do with this? We could create a new section on the webpage with user contributed Command classes (that are not and will not be transferred to JXLS master)
