### ISSUE TITLE
Duplicate class Error

### ISSUE THREAD

**Issue by sami-soft** [jxlsteam/jxls#137]
Duplicate class org.apache.commons.logging.Log found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)
Duplicate class org.apache.commons.logging.LogConfigurationException found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)
Duplicate class org.apache.commons.logging.LogFactory found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)
Duplicate class org.apache.commons.logging.impl.NoOpLog found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)
Duplicate class org.apache.commons.logging.impl.SimpleLog found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)
Duplicate class org.apache.commons.logging.impl.SimpleLog$1 found in modules jetified-commons-logging-1.2 (commons-logging:commons-logging:1.2) and jetified-jcl-over-slf4j-1.7.30 (org.slf4j:jcl-over-slf4j:1.7.30)

**Comment by SoltauFintel** [comment]
You should supply more informations.

**Comment by sami-soft** [comment]
> You should supply more informations.

 
I added this library in gradle dependencies  Android Studio :
 implementation 'org.jxls:jxls-poi:2.10.0'

and it syncs properly but an error Duplicate class appears when I try to run the app

**Comment by SoltauFintel** [comment]
You should check the dependencies. Have you examined the "gradle dep" output?!
