### ISSUE TITLE
Multi-if using

### ISSUE THREAD

**Issue by PofigistVip** [jxlsteam/jxls#144]
Hello!
I am creating a report where the display of a row depends on its rowType. 'if' works fine, but after all data, empty lines from the template are printed at the end of the report. I tried to solve the problem by changing the lastCell of root area, but (if the lines with 'if' are not entered in this area) jx comments remain in the report.
I attach the template and the results.
Thank you for any help!
[issue.zip](https://github.com/jxlsteam/jxls/files/7072457/issue.zip)

Template:
Yep, the last 4 lines do not have fields for output, but they will be there - i can not set these lines statically.
![image](https://user-images.githubusercontent.com/47919592/131250175-47aea5d0-e421-4e13-9e2d-ece57a79d60b.png)
Result (The last three lines should not be):
![image](https://user-images.githubusercontent.com/47919592/131250195-55f91c2c-ad13-495d-8268-14d506a94c67.png)

**Comment by SoltauFintel** [comment]
Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.

**Comment by SoltauFintel** [comment]
I think if you want to work with rowTypes, JXLS is not the right framework. Then use POI directly.

Or a jx:each over all items (like row 4). And then at the end either a mandatory Sum line (row 5) or an Avg line (row 6). The jx:if would be in row 5. Around jx:each(items) and jx:if(sum or avg) then a outer jx:each for all the blocks.
