### ISSUE TITLE
Updating row heights on template with multiple areas (using applyAt)

### ISSUE THREAD

**Issue by jools-uk** [jxlsteam/jxls#147]
Given a template with multiple jx:area defined, one after the other, with a static top region for each area, and when using xlsArea.applyAt() to transform the areas, updateRowHeights does not correctly copy the height from the source cell. It seems to attempt to lookup the transformed location in the source area and will not find a hit if rows/cols have been added to a prior area. I suspect issue is srcRow, which is not looking at the real source.

**Comment by jools-uk** [comment]
Add PR with proposed fix:
https://github.com/jxlsteam/jxls/pull/150

**Comment by SoltauFintel** [comment]
Another PR #154 with my code-review. Will be part of release 2.12.0.
