### ISSUE TITLE
conditional formatting cause Performance issue

### ISSUE THREAD

**Issue by lujuliang** [jxlsteam/jxls#152]
Hi Team, I want to set alternate row color in template, I refer to 'set conditional formatting to apply banded rows or columns' on
https://support.microsoft.com/en-us/office/apply-color-to-alternate-rows-or-columns-30002ce0-7a1c-4d70-a70c-4b6232f09f5e.
I used this formula: =MOD(ROW(),2)=0 to set a gray row, when the rows length more than 1000, it is very slowly to download the exported file.
Backend:
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                InputStream is = ReportsController.class.getResourceAsStream("reportTemplate.xlsx");
                Context context = new Context();
                context.putVar("report", report);
                _JxlsHelper.getInstance().processTemplate(is, bos, context);_

It takes more than 20 minutes to download 3,000 rows of data.
If I removed the conditional formatting roles it only takes a few seconds.
How can I fix this issue? Could anyone give me some advice? Thank you so much.

**Comment by SoltauFintel** [comment]
I think the XLSX file gets too big. POI has to handle a lot XML elements in memory. The solution for that is the use of **streaming**. Please study https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/templatebasedtests/TableTest.java
