### ISSUE TITLE
How to specify custom write logic for specific cell

### ISSUE THREAD

**Issue by fedotxxl** [jxlsteam/jxls#158]
I wanna programmatically write value to a cell. How can I do it? I tried to use `CellDataUpdater` but didn't find any way to access `org.apache.poi.ss.usermodel.Cell` and call `cell.setCellValue`

**Comment by leonate** [comment]
Indeed, `org.apache.poi.ss.usermodel.Cell` is a private field of the `PoiCellData` which is a parameter to the `CellDataUpdater`.

The idea was to use `setEvaluationResult()` to set a value of the cell to be later written by a Transformer.
You can also modify a cell style as shown in [UpdateCellDemo](https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/UpdateCellDemo.java).

Theoretically, nothing prevents you from getting `XlsArea` from the `CellData` and then get a `PoiTransformer` from it to get an access to the POI workbook object. But that might be too complicated, so my advise would still be to try to use `setEvaluationResult()`.

If really needed we can make `cell` field in the `PoiCellData` accessible by creating a getter for it, but not sure if it would be a good practice.
