### ISSUE TITLE
JXLS Parallel Sheet Write Support

### ISSUE THREAD

**Issue by vaibhavk311** [jxlsteam/jxls#165]
Hey Team,
We have use-case where we need to add multiple sheets with each sheet containing 8 lac rows.
I wanted to check that can we add **Multi sheet Parallel Writing** support to optimise performance of the JXLS. 

Any help would be appreciated :)

**Comment by vaibhavk311** [comment]
Adding @SoltauFintel

**Comment by SoltauFintel** [comment]
What do you mean with "8 lac rows"? How many sheets and rows do you plan? (I ask myself if it's really necessary...)

**Comment by vaibhavk311** [comment]
@SoltauFintel 
We are planning for 8 lac rows per sheet. And total sheet at max is close to 20. 
That's where i was thinking that can writing operation to all sheets be done paralely.

**Comment by SoltauFintel** [comment]
I still don't understand what you mean with "8 _lac_ rows". Can you describe it in other words?

If you mean 20 sheets with 8 rows - I think a parallel operation is oversized.

**Comment by vaibhavk311** [comment]
@SoltauFintel 
Yeah basically 20 sheets with 0.8 million rows in every sheet.

Writing paralely to every sheets will reduce the overall time. How will it become oversized ? 
Didn’t get that

**Comment by SoltauFintel** [comment]
Ok, "8 lac rows" = "800,000 rows". Optimization makes sense for this, of course.

I suggest you fork the repo and develop it there. Please don't submit the PR for the next release. I think it's a too big change for the next release.

**Comment by vaibhavk311** [comment]
@SoltauFintel Yeah Sure thanks :)

**Comment by SoltauFintel** [comment]
Closed because nothing more happened here. Please reopen if necessary.
