### ISSUE TITLE
IndexOutOfBoundsException in StandardFormulaProcessor

### ISSUE THREAD

**Issue by SoltauFintel** [jxlsteam/jxls#173]
I use a snapshot build including #73 with activated exception throwing. A testcase fails:

```
AreaRef formulaTargetAreaRef = formulaCellData.getTargetParentAreaRef().get(i);
```

Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1  
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)  
	at java.util.ArrayList.get(ArrayList.java:433)  
	at org.jxls.formula.StandardFormulaProcessor.processAreaFormulas(StandardFormulaProcessor.java:63)  
	at org.jxls.area.XlsArea.processFormulas(XlsArea.java:571)  
	at org.jxls.util.JxlsHelper.processTemplate(JxlsHelper.java:273)  

@leonate Can you fix this without a testcase? I can't publish a testcase for this ugly complex report. But I can test it with our testcase from your feature branch.

**Comment by SoltauFintel** [comment]
I suggest we use PoiExceptionThrower temporarily. Maybe then our unit tests will fail as well.

**Comment by leonate** [comment]
How to reproduce it?

**Comment by SoltauFintel** [comment]
I can't deliver you informations about how to reproduce it. If you change something in a feature branch I can test it with my unit test.

**Comment by SoltauFintel** [comment]
I have tried to rebuild a testcase - but there's no error...

I can give you some debug informations from the real world testcase at the point where IndexOutOfBound happens (StandardFormulaProcessor.java:63):
formulaCellData.getTargetParentAreaRef() has 1 AreaRef "GEC!A1:O41".
targetFormulaCells has at index 0 a CellRef "GEC!B6" and at index 1 a CellRef "GEC!B6".
formulaCellData: CellData{GEC!B6, cellType=FORMULA, cellValue="benchmark (Rdam + "&C6&" $/mt)"}
formulaCells: 49 items
targetFormulaString: "benchmark (Rdam + "&C6&" $/mt)"
1 xlsArea with start=GEC!A1, size=(8,41), parentCommand=null. Streaming is not used.
If I empty GEC!B6 there's no exception.
B6 is not part of jx:each or so. Column C has width 0. C6 has this command: jx:each(items="budgets", var="budget", lastCell="C6") and content: ${budget.intoPlaneDifferential}

**Comment by SoltauFintel** [comment]
possibly similar to https://bitbucket.org/leonate/jxls/issues/207
commit 23dff19af

**Comment by SoltauFintel** [comment]
@leonate Cause is commit e4f31b

**Comment by leonate** [comment]
I tried to identify the issue by just looking at the code but it is really hard to understand what is the root cause. 
From the debug information you shared above, it looks like `targetFormulaCells` was populated with a redundant item (two times "GEC!B6"). Which would meant that XlsArea.updateCellDataArea() was invoked more times than needed. Perhaps it is connected to the changes in CellRange.isExcluded() method or in XlsArea.transformStaticCells() which happended in commit e4f31bd . 
But it is difficult to see why does it happen. Usually I seek such errors by debugging a particular test case. Try and error method will take much more time.

**Comment by SoltauFintel** [comment]
debugging XRPositionTakingTraderReport because of duplicate Summary!B10 entry
breakpoint in CellData.addTargetPos():

### 1st call

cellRef: Summary!B10
targetPos id=327
this id=317: CellData{Summary!B10, cellType=FORMULA, cellValue=SUM(B9)}

call stack:
PoiCellData(CellData).addTargetPos(CellRef) line: 227	
XlsArea.updateCellDataArea(CellRef, CellRef, Context) line: 538	
XlsArea.transformStaticCells(CellRef, Context, int, int, int, int) line: 517	
XlsArea.applyAt(CellRef, Context) line: 178	
JxlsHelper.processTemplate(Context, Transformer) line: 268	
ProcessTemplateJxlsFeature.apply(JxlsEngineContext) line: 25	

### 2nd call

cellRef: Summary!B10
targetPos id=327
this id=317: CellData{Summary!B10, cellType=FORMULA, cellValue=SUM(B9)}

call stack:
- PoiCellData(CellData).addTargetPos(CellRef) line: 227	
- XlsArea.updateCellDataArea(CellRef, CellRef, Context) line: 538	
- XlsArea.transformStaticCells(CellRef, Context, int, int, int, int) line: 517 // row:9,col:1,offsetRow:0,startCol:0, cellRange contains "[Summary!A10, Summary!B10, null, Summary!Q10, Summary!R10, Summary!S10]"
- **XlsArea.transformStaticCells(CellRef, Context, AreaRef) line: 260** // rSRow:2, rSCol:3
- XlsArea.applyAt(CellRef, Context) line: 242 // cellRef: Summary!A1, commandsArea: C3:C25	
- JxlsHelper.processTemplate(Context, Transformer) line: 268

**Comment by leonate** [comment]
Can you share more data variables from the 1st call to transformStaticCells() at `XlsArea.applyAt(CellRef, Context) line: 178` ?
I suspect this call should not have happened, so perhaps the condition has to be fixed.

**Comment by iamforrest** [comment]
@leonate I have tested the last codes, and I found that rows between commands still lost. After I debugged the codes, I found that line 178 in XlsArea.java:

`transformStaticCells(cellRef, context, startRow, 0, startRow, startCol - 1);`

should change to

`transformStaticCells(cellRef, context, lastProcessedRow, 0, startRow, size.getWidth() - 1);`

I am not sure whether it is a perfect solution for this issue. Hope it helps.  Thanks.

**Comment by leonate** [comment]
Nice findings @iamforrest , I will check if it works with my test case and share the results.

**Comment by leonate** [comment]
Unfortunately the proposed change does not work with my test case, but there is another solution which I am testing currently. Maybe the proposed change also has to be made but we need a test case proving that it solves an issue.

**Comment by SoltauFintel** [comment]
@leonate Unfortunately, the error still occurs with commit 5107f58. (issue-173-test)
