### ISSUE TITLE
support for java 11 and 17 at build time

### ISSUE THREAD

**Issue by mosidev** [jxlsteam/jxls#178]
* spock framework needs to be updated and because of that the junit needs to changed to junit-vintage
* maven surefire version needs to be updated in the jxls module
* maven source and javadoc plugins needs to be updated
* to sync mockito and cglib versions between maven and gradle they should be updated
* java 8 ZonedDateTime return time with millisecond and java 11+ return time with nanosecond, so the JSR310Test.testInstant() unit test needs to be changed to work with java 8 and above

For these changes, the minimum version of Java does not need to be updated and version 8 will remain.

**Comment by SoltauFintel** [comment]
a) I don't know Java higher than version 8. Which JDK are you using? (exact name+version)

b) What is the difference between JUnit 4 and JUnit Vintage 5?

c) Actually we want to get rid of the spock based test cases. (Who wants to change them?)

d) I have the impression that only src/test is affected. I have to test whether everything still works for me (with Gradle)... leonate would have to check that with Maven.

**Comment by SoltauFintel** [comment]
see PR #179  
and  #212

**Comment by SoltauFintel** [comment]
closed, as PR is already merged
