### ISSUE TITLE
Each Command using markup language doesn't read "items" attr

### ISSUE THREAD

**Issue by sachin-surya-soft** [jxlsteam/jxls#186]
I was using markup language to map list on excel as mentioned in demo, but it was always giving me error that `source is null`. Then I debugged it and realized that it is not reading `items` attr from comment.
When I set value for items in `EachCommand` class manually using debugger, then things work fine.

The regex matcher doesn't consider `items` as attr, hence it is not adding it in command attr map.

My command:
![Screenshot from 2022-03-29 16-17-49](https://user-images.githubusercontent.com/65755403/160595179-d32674a1-6652-40b0-b927-a722dcc34153.png)

Value of items is null

![Screenshot from 2022-03-29 16-17-13](https://user-images.githubusercontent.com/65755403/160595107-62ab307a-1a37-47ef-bc4f-5758a3f18742.png)

**Comment by SoltauFintel** [comment]
What version do you use?

I guess we'll need a testcase (Excel template + Java code).

**Comment by sachin-surya-soft** [comment]
Version: `2.11.0`

I cannot share the excel template, but I can share the commands I have used in markup.

Code: 

```
val inputSteam = FileInputStream(File(this::class.java.getResource(TEMPLATE)!!.toURI()))
val outputStream = FileOutputStream(File(this::class.java.getResource(OUTPUT)!!.toURI()))
val context = Context()
context.putVar("statement", statement)
JxlsHelper.getInstance().processTemplateAtCell(inputSteam, outputStream, context, "Template!A1")
```

**Comment by SoltauFintel** [comment]
Is there a jx:area command in the template? (need to know cell refs and jx: commands)

What JDK & version do you use?

Have you tried to recreate the template file from scratch using only MS Excel?

**Comment by SoltauFintel** [comment]
There is a typo in items?!! satement vs. statement

**Comment by SoltauFintel** [comment]
Does it work if you use items="summaries"? (with putting it to Context)

**Comment by SoltauFintel** [comment]
I have tried to reproduce with Highlight2Demo.java (and Java 8). Cannot reproduce.

**Comment by sachin-surya-soft** [comment]
> Is there a jx:area command in the template? (need to know cell refs and jx: commands)
Yes, I have given area command and after that only this command comes.
> What JDK & version do you use?
Java 8
> Have you tried to recreate the template file from scratch using only MS Excel?
Nope.

**Comment by sachin-surya-soft** [comment]
> There is a typo in items?!! satement vs. statement

Even after fixing that is not working.

**Comment by sachin-surya-soft** [comment]
> Does it work if you use items="summaries"? (with putting it to Context)

I have tried that, not working.

**Comment by sachin-surya-soft** [comment]
> I have tried to reproduce with Highlight2Demo.java (and Java 8). Cannot reproduce.

Aah ohkay. This is kotlin code, one of my team tried it out with java, he faced the same issue. But then he gave getters & setters to variables it worked for him. In kotlin it is not working.

**Comment by sachin-surya-soft** [comment]
It worked when I tried editing using MS Excel. Thanks for your support. 
It would be good if we mention this in documentation that only use MS Excel for editing template, otherwise one would spend too much time in figuring out what went wrong.

**Comment by SoltauFintel** [comment]
AFAIK jxls is not tested with Kotlin or Java > 8

**Comment by SoltauFintel** [comment]
Yes, please only edit jxls templates with Microsoft Excel. We will check the documentation.
