### ISSUE TITLE
Rows are getting merged in single row in jxls 2.11.0

### ISSUE THREAD

**Issue by ankurkumarHL** [jxlsteam/jxls#189]
Hi, we have upgraded jxls from 2.6.0 to 2.11.0 and we observed in one of the template the few rows are getting merged in to one row while jx:each & direction="down". Is there any changes or fix with 2.11.0 release regarding this?

**Comment by SoltauFintel** [comment]
I don't know if there has been a relevant change between 2.06 and 2.11. Please check it with the versions between 2.06 and 2.11. What is the 1st version that causes the problem?

Please send us an pull request with an example.

**Comment by SoltauFintel** [comment]
Closed due to no reply
