### ISSUE TITLE
sxssf with chart

### ISSUE THREAD

**Issue by MVTalent** [jxlsteam/jxls#196]
Good day!
Used library version 2.6.0. 
I want to form a chart on a sheet using dynamic named ranges. The problem is that when using the streaming PoiTransformer (SXSSF), the diagram is not displayed, it is simply not on the resulting tab. Moreover, when using a non-streaming PoiTransformer, the diagram is displayed correctly.
[chart_sheet_template.xlsx](https://github.com/jxlsteam/jxls/files/8806112/chart_sheet_template.xlsx)
[wiht_sxssf.xlsx](https://github.com/jxlsteam/jxls/files/8806113/wiht_sxssf.xlsx)
[without_sxssf.xlsx](https://github.com/jxlsteam/jxls/files/8806114/without_sxssf.xlsx)
Thanks in advance!

**Comment by SoltauFintel** [comment]
Solution:

Put chart on its own sheet, use the SelectSheetsForStreamingPoiTransformer and don't specify the sheet name of the chart.

https://github.com/jxlsteam/jxls/blob/a2c69bedfdbf01067e9e1d6d4df598eff8b71c8c/jxls-poi/src/test/java/org/jxls/templatebasedtests/TableTest.java

**Comment by MVTalent** [comment]
What if the chart is built on a large number of records, for example 50000?

**Comment by MVTalent** [comment]
> Solution:
> 
> Put chart on its own sheet, use the SelectSheetsForStreamingPoiTransformer and don't specify the sheet name of the chart. So streaming is not used for that sheet. Streaming is intended for stupid but long data lists.
> 
> https://github.com/jxlsteam/jxls/blob/a2c69bedfdbf01067e9e1d6d4df598eff8b71c8c/jxls-poi/src/test/java/org/jxls/templatebasedtests/TableTest.java

This option works even if you specify a sheet with a chart!
