### ISSUE TITLE
batch append

### ISSUE THREAD

**Issue by MVTalent** [jxlsteam/jxls#197]
Good day!
Is there a way to batch add lines to the output file? Let's say I have several thousand records and I want to add records to a file (using the "each" command), for example 5000. Is there any mechanism for this?

**Comment by SoltauFintel** [comment]
I don't understand. Please add an expected Excel file and a template.

**Comment by MVTalent** [comment]
For example, we have a list of 100,000 employees (`List<Employee>`). Now I need to batch (in a cycle), for example, add 5000 employees to the file. Algorithm:
[test_result.xlsx](https://github.com/jxlsteam/jxls/files/8850350/test_result.xlsx)
[test_template.xlsx](https://github.com/jxlsteam/jxls/files/8850351/test_template.xlsx)


1. got the first 5,000 employees
2. recorded the received employees in a file
3. perform step 1 - step 2 while we have data

As a result, all 100,000 employees should be in the resulting file

**Comment by SoltauFintel** [comment]
With file you mean an Excel file?!

So you want to write the XLSX file and add more rows in a further step. (But wouldn't it be easier to first collect all the data (somewhere else) and only create the final file at the end?)

I think using notes wouldn't make sense here. I could imagine that this could be done with Java programming and EachCommand (or EachAction??). But I have no experience there.

**Comment by MVTalent** [comment]
> With file you mean an Excel file?!

Yes

> So you want to write the XLSX file and add more rows in a further step. (But wouldn't it be easier to first collect all the data (somewhere else) and only create the final file at the end?)

Now this is done - the data is collected in one large list, for example, 500,000 employees. But the fact is that there is a limit on the memory of the jvm heap and therefore I would like to receive not the entire list at once, but piece by piece and add these pieces to the excel file.

> I think using notes wouldn't make sense here. I could imagine that this could be done with Java programming and EachCommand (or EachAction??). But I have no experience there.

The `jx:each` command is currently used to iterate through the entire list. I don't understand how you can batch add using the `jx:each` command...
It looks like there is no way for jxls to batch add data

**Comment by MVTalent** [comment]
> I didn't mean jx:each (=notes), I meant defining the JXLS areas using Java code (not notes).

And how do you indicate in which cell what to write in this case?
If you use commands in notes, then you can do it like this:

![image](https://user-images.githubusercontent.com/14983919/172774583-132689cf-38be-4c0b-8586-fdab8a6c3bf8.png)

And what will it look like when using Java code?

**Comment by SoltauFintel** [comment]
I can't help further as I have no experience in this area.

If necessary, you must use Apache POI instead of JXLS.

**Comment by MVTalent** [comment]
> If necessary, you must use Apache POI instead of JXLS.

I just do not understand how to write line by line using JXLS streaming, but for JXLS we must specify the context. Even if you create JXLS areas/EachCommand using Java, it is not clear how to add one line to the report. With Apache POI, there are no problems in building a report...
