### ISSUE TITLE
Java >14 records support

### ISSUE THREAD

**Issue by rimvydasb** [jxlsteam/jxls#218]
Java records, introduced in Java 14, out-of-the-box support is necessary.

If the plain record is used:
`record FlatResult(String requirement) {}`

with an expression: `${ar.requirement}`

we have an output:
`org.jxls.expression.JexlExpressionEvaluator.evaluate:65@1:14![2,14]: 'ar.requirement' unsolvable property 'requirement' `

One possible workaround would be a Lombok getter that adds boilerplate:
`record FlatResult(@Getter String requirement) {}`

**Comment by SoltauFintel** [comment]
Is it maybe because Apache JEXL doesn't support Java >=14 records? You would have to open a ticket there first.

JXLS uses JEXL as expression language. Everything inside ${...} is JEXL.

**Comment by SoltauFintel** [comment]
Maybe this workaround would be possible:

```
public class RecordTool {
   public Object field(Object record, String fieldName) {
   // implementation ...
}}
context.put("R", new RecordTool());

// in Excel cell:
${R.field(foo, 'bar')}
```
