### ISSUE TITLE
Support the dx1,dy1,dx2,dy2 while drawing the image

### ISSUE THREAD

**Issue by nww57** [jxlsteam/jxls#22]
I see the source code in addImage `ClientAnchor anchor = helper.createClientAnchor();`  it can setDx1,setDy1,setDx2,setDy2;maybe we can develop this function for the image;

**Comment by SoltauFintel** [comment]
Feel free to fork this repo, add the dx1/dx2/dy1/dy2 feature to ImageCommand and send a PR. Internally dx1/dx2/dy1/dy2 should be an Integer. If null no action. Otherwise call setter of ClientAnchor in addImage. Please also add a testcase.

**Comment by SoltauFintel** [comment]
No response. Ticket will be closed 2020-05-22.
