### ISSUE TITLE
[jxlsteam/jxls] org.jxls.util.CannotOpenWorkbookException: org.apache.poi.ooxml.POIXMLException: Element styles@http://schemas.openxmlformats.org/wordprocessingml/2006/main is not a valid styleSheet@http://schemas.openxmlformats.org/spreadsheetml/2006/main document or a valid substitution. (Issue #223)

### ISSUE THREAD

**Issue by shixinlei1998** [jxlsteam/jxls#224]
What's the problem? It's better if I upload the template again. I will report this error later. What is MS Excel

**Comment by SoltauFintel** [comment]
MS Excel = Microsoft Excel

**Comment by shixinlei1998** [comment]
The template made by MS Excel is used. I have put the template on the attachment. Just upload the template again. It won't work again later. Could you tell me why? I can't start now




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jxlsteam/jxls"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jxlsteam/jxls] [jxlsteam/jxls] org.jxls.util.CannotOpenWorkbookException: org.apache.poi.ooxml.POIXMLException: Element ***@***.***://schemas.openxmlformats.org/wordprocessingml/2006/main is not a valid ***@***.***://schemas.openxmlformats.org/spreadsheetml/2006/main document or a valid substitution. (Issue #223) (Issue #224)





 
MS Excel = Microsoft Excel
