### ISSUE TITLE
Is grouping with more than one level supported?

### ISSUE THREAD

**Issue by edu-de** [jxlsteam/jxls#228]
Hi,

we want to use the newest JXLS 2.12.0 for grouping two levels, similar as explained here: https://jxls.sourceforge.net/samples/grouping_example.html

The grouping example above uses one grouping level and uses the variable "_group.items" for accessing the items in the group, but how to create a second grouping inside the first one ? It would need something as "_group1.items".

Is this supported by JXLS?

**Comment by edu-de** [comment]
Ok, the answer seems to be found here:
https://jxls.sourceforge.net/reference/each_command.html

using the "var" attribute (You can also skip the var attribute altogether and in this case the default group variable name will be _group.) 

We will test this. 

Imho, this information should also be found here:  https://jxls.sourceforge.net/samples/grouping_example.html

**Comment by SoltauFintel** [comment]
> Imho, this information should also be found here: https://jxls.sourceforge.net/samples/grouping_example.html

It's already described there!?
