### ISSUE TITLE
POI 4.1.2 security issue and upgrade to 5.2.3

### ISSUE THREAD

**Issue by edu-de** [jxlsteam/jxls#229]
Hi,

POI 4.1.2 has this security issue https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapache&cpe_product=cpe%3A%2F%3Aapache%3Apoi&cpe_version=cpe%3A%2F%3Aapache%3Apoi%3A4.1.2 

so we decided to upgrade to POI 5.2.3. 

The jxls code works and we didn't find any places necessary to change any jxls code.
Are you planning to upgrade POI to 5.2.3 soon ? Or do you know any issue we may have overseen ?
If we didn't miss anything JXLS 2.12.0 supports POI 5.2.3 without any code changes, so the upgrade should be quite straightforward.

**Comment by SoltauFintel** [comment]
scratchpad and not poi has this problem.
