### ISSUE TITLE
 the command after AZ is invalid?

### ISSUE THREAD

**Issue by liaoxuewei** [jxlsteam/jxls#233]
It seems that the command after AZ is invalid? Like below issue?
https://github.com/jxlsteam/jxls/issues/60

Also like below?
IssueB167Test.java ==> Excel templates context variable not found if used beyond column AZ

**Comment by SoltauFintel** [comment]
Solution: modify PoiTransformer.lastCommentedColumn

**Comment by liaoxuewei** [comment]
OK，it works, thanks.
