### ISSUE TITLE
How to convert BigDecimal data types when importing

### ISSUE THREAD

**Issue by liyingcold** [jxlsteam/jxls#249]
Hello，I have some BigDicemal type of datas ,But I found an error during the conversion and couldn't parse it.
For example error  info
![Q%Y)7TLBN 4Y{VD@@~ IWGI](https://github.com/jxlsteam/jxls/assets/46558390/5dc14654-09ae-4594-98f4-890d088c4b80)
![NY)DGA6BK OJBF4`8%OV7GI](https://github.com/jxlsteam/jxls/assets/46558390/3ea9ab6f-b76f-433b-8fc7-429dd8cfcb96)
![image](https://github.com/jxlsteam/jxls/assets/46558390/d921dde6-8f3b-4c10-aa38-e7619b6ec447)

**Comment by liyingcold** [comment]
I don't know if jxls supports BigDecimal, but I can convert it correctly by changing the type to Double. So does jxls support the conversion of BigDecimal?
I mean that may not be  a bug,In RederConfig.clss, BigDecimal was not registered in the ConvertUtilsBean when initializing the converter.
![NPP}UVPU{E V1X44A58H2ZM](https://github.com/jxlsteam/jxls/assets/46558390/7ab89c73-505d-4fef-9ad5-5292c726fab1)

**Comment by leonate** [comment]
I guess, if it is not registered probably the support is not built-in. You can try to implement your own Converter and register it through Apache Commons BeanUtils as it is mentioned in the jxls-reader doc.

**Comment by liyingcold** [comment]
OK,thanks for your advice. I'll try it tomorrow.

**Comment by liyingcold** [comment]
Sorry, I made a mistake in my code. It can parse BigDecimal data normally
