### ISSUE TITLE
Remove lastCommentedColumn

### ISSUE THREAD

**Issue by gastendonk** [jxlsteam/jxls#251]
We should get rid of the lastCommentedColumn function. It is only used in readCommentsFromSheet(). The Sheet class has `Map<CellAddress, ? extends Comment> getCellComments()` for receiving all comments.

Developers are surprised that their JXLS comments don't work anymore because they don't know about this feature.

**Comment by SoltauFintel** [comment]
see PR #267

**Comment by gastendonk** [comment]
This is a breaking change. You just have to remove calls to setLastCommentedColumn() and everything works.
