### ISSUE TITLE
Memory leak when generate excel around 300,000 rows

### ISSUE THREAD

**Issue by renjunzhou** [jxlsteam/jxls#26]
java heap space OOM then

**Comment by SoltauFintel** [comment]
An Excel file can contain 1 million rows. I have a testcase for that and it works.

Please use streaming.

**Comment by zheng59** [comment]
When I use XLSX and stream it, the program creates a lot of CellRef objects.  These objects are released only when the file is processed.

**Comment by leonate** [comment]
@zheng59 , you should use SXSSF streaming transformer to keep the memory usage low. Like in this example https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/stress/SxssfDemo.java .
