### ISSUE TITLE
When using direction="RIGHT", the fixed area on the far right disappears

### ISSUE THREAD

**Issue by OhunterO** [jxlsteam/jxls#265]
When using direction="RIGHT", the fixed area on the far right disappears
![1693757949909](https://github.com/jxlsteam/jxls/assets/10428290/1df4110c-7f7d-416e-8151-294f6efa6376)
Refer to the screenshot, the yellow area has disappeared。What should I do to achieve the desired effect。Thanks
[expected.xlsx](https://github.com/jxlsteam/jxls/files/12506545/expected.xlsx)
[temp.xlsx](https://github.com/jxlsteam/jxls/files/12506546/temp.xlsx)
[actual.xlsx](https://github.com/jxlsteam/jxls/files/12506547/actual.xlsx)

**Comment by OhunterO** [comment]
version:
   jxls:2.13.0
   jxls-poi:2.13.0

**Comment by leonate** [comment]
Is it reproducible with previous Jxls versions?
Does it work in a regular mode (without Sxssf)?

**Comment by OhunterO** [comment]
> Is it reproducible with previous Jxls versions? Does it work in a regular mode (without Sxssf)?

It works in the Sxssf mode.

**Comment by SoltauFintel** [comment]
> It works in the Sxssf mode.

In what version? If in current we can close this ticket?

**Comment by OhunterO** [comment]
> 2.13.0

2.13.0

> > It works in the Sxssf mode.
> 
> In what version? If in current we can close this ticket?

2.13.0
