### ISSUE TITLE
Memory Leak in Streaming Excel Processing

### ISSUE THREAD

**Issue by giuseppemilicia** [jxlsteam/jxls#271]
In the current implementation of the streaming Excel processing, a memory leak occurs due to the line `cellData.addTargetParentAreaRef(newAreaRef);` in the `XlsArea` class. This issue persists even when `isFormulaProcessingRequired` is set to false, preventing the proper dereferencing of CellRef objects.

**Comment by bole915226051** [comment]
是什么情况下会触发这个问题。因为大批量导入的功能，我已经尝试生产使用2.13版本了。

**Comment by giuseppemilicia** [comment]
The issue arises when using a formula field in excel in conjunction with streaming. It may be triggered with version 2.13.

**Comment by bole915226051** [comment]
> 当将 Excel 中的公式字段与流式传输结合使用时，就会出现此问题。2.13版本可能会触发。

升级jxls到2.13版本，因为我是想使用SXSS的流功能用于节省内存。请问什么时候会更新版本。
或者说有没有低一点的版本适用于生产环境呢。

**Comment by SoltauFintel** [comment]
@bole915226051 Please write in English.

**Comment by bole915226051** [comment]
> 成员

Okay, get it

**Comment by bole915226051** [comment]
May I ask when this code will be launched?

**Comment by gastendonk** [comment]
@giuseppemilicia  @bole915226051  released today, available on Maven Central maybe in up to two days
