### ISSUE TITLE
IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalStylesheet

### ISSUE THREAD

**Issue by uek06** [jxlsteam/jxls#304]
Hello,

Version used : 2.13.0

When using the library with SXSSF streaming, an error appears in the console :

> java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalStylesheet
> 	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
> 	at org.apache.poi.util.XMLHelper.trySet(XMLHelper.java:284)
> 	at org.apache.poi.util.XMLHelper.getTransformerFactory(XMLHelper.java:225)
> 	at org.apache.poi.util.XMLHelper.newTransformer(XMLHelper.java:231)
> 	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:56)
> 	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:68)
> 	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:450)
> 	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:563)
> 	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1490)
> 	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
> 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:968)

The file is correctly generated, but it is annoying to have this in the console.
This is my code : 
```
Workbook workbook = WorkbookFactory.create(is);
PoiTransformer transformer = PoiTransformer.createSxssfTransformer(workbook);
AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
List<Area> xlsAreaList = areaBuilder.build();
Area xlsArea = xlsAreaList.get(0);
Context context = new Context();
for (Map.Entry<String, Object> entry : model.entrySet()) {
       context.putVar(entry.getKey(), entry.getValue());
}
String oldSheetName = workbook.getSheetName(0);
// create new sheet called Result and start in A1
xlsArea.applyAt(new CellRef("Result!A1"), context);
context.getConfig().setIsFormulaProcessingRequired(false);
// processing
workbook.setForceFormulaRecalculation(true);
Workbook workbookProcessed = transformer.getWorkbook();
// remove template sheet
workbookProcessed.removeSheetAt(0);
// set Result sheet name to old name
workbook.setSheetName(0, oldSheetName);
workbookProcessed.write(outputStream);
```

Could you please have a look ? 

Thanks

**Comment by SoltauFintel** [comment]
Excusez-moi. This looks like an Apache POI or Xalan problem to me. I.e. it is not relevant to Jxls and therefore I am closing this ticket.

If streaming doesn't work, don't use it. :-)
