### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by sizzlecar** [jxlsteam/jxls#31]
`
            
           <dependency>
                <groupId>org.jxls</groupId>
                <artifactId>jxls</artifactId>
                <version>2.8.1</version>
            </dependency>

            <dependency>
                <groupId>org.jxls</groupId>
                <artifactId>jxls-reader</artifactId>
                <version>2.0.6</version>
            </dependency>

            <dependency>
                <groupId>org.jxls</groupId>
                <artifactId>jxls-poi</artifactId>
                <version>2.8.1</version>
            </dependency>

          try (InputStream templateXmlStream = ExcelUtils.class.getResourceAsStream(xmlFile);
             InputStream inputXlsStream = new BufferedInputStream(inputXls)) {
            XLSReader reader = ReaderBuilder.buildFromXML(templateXmlStream);
            ReaderConfig.getInstance().setSkipErrors( true );
            XLSReadStatus readStatus = reader.read(inputXlsStream, beanMap);
            if (!readStatus.isStatusOK()) {
                throw new BusinessException("读取excel发生错误");
            }
        } catch (Exception e) {
            logger.error("读取excel发生错误", e);
            throw new BusinessException("读取excel发生错误");
        }

java.io.IOException:java.lang.ClassNotFoundException:org.apache.poi.xssf.usermodel.XSSFWorkbookFactory

`

**Comment by SoltauFintel** [comment]
jxls-reader is not supported by this repo. Please use https://bitbucket.org/leonate/jxls-reader/src/master/

However, I fear that no processing will take place there either. It would be better if you clone the repo and fix the bug yourself (POI version incompatibility?).
