### ISSUE TITLE
SimpleExporter  should have function that accepts other data to be passed as context in case of custom template scenario.

### ISSUE THREAD

**Issue by NaglaaKharroub** [jxlsteam/jxls#315]
gridExport(Iterable<?> headers, Iterable<?> dataObjects, String objectProps, OutputStream outputStream) 

the gridExport function accepts only header and data object, how ever for cutom grid templates there might be other variables that need to be passed to the context 

I suggest adding overloaded version with possibility of SimpleExporter  client to pass full map of data needed for their custom template

**Comment by SoltauFintel** [comment]
I've pushed PR #316. With that change you have full control over the data map. Will be released in version 3.1.
