### ISSUE TITLE
IllegalArgumentException for SxssfTransformer

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#32]
Hi,

We are trying to switch to SxssfTransformer to support JXLS2 in large files.

Currently, we use this:

    JxlsHelper.getInstance().processTemplate(is, os, context);

So we changed to:

    Transformer transformer = PoiTransformer.createSxssfTransformer(workbook, 5, false);  
    AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);  
    List<Area> xlsAreaList = areaBuilder.build();  
    for (Area xlsArea: xlsAreaList) {  
       xlsArea.applyAt(new CellRef(xlsArea.getStartCellRef().getCellName()), context);  
    }  
    context.getConfig().setIsFormulaProcessingRequired(false); // with SXSSF you cannot use normal formula processing  
    workbook.setForceFormulaRecalculation(true);  
    workbook.setActiveSheet(1);  
    ((PoiTransformer) transformer).getWorkbook().write(os);

But we are getting this error:
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    java.lang.IllegalArgumentException: Sheet index (1) is out of range (0..0)
    at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1470)
    at org.apache.poi.xssf.usermodel.XSSFWorkbook.setActiveSheet(XSSFWorkbook.java:1449)
    at maventest.MavenTest.main(MavenTest.java:56)

If we change

    for (Area xlsArea: xlsAreaList) {
        xlsArea.applyAt(new CellRef(xlsArea.getStartCellRef().getCellName()), context);
    }

to

    for (Area xlsArea: xlsAreaList) {
       xlsArea.applyAt(new CellRef("Result!A1"), context);
    }

it works. I don’t understand this. I want to use a generic way, so xlsArea.getStartCellRef().getCellName() should also work, or what am I doing wrong? Is this a bug?

The complete test case is this:

```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.jxls.area.Area;
import org.jxls.builder.AreaBuilder;
import org.jxls.builder.xls.XlsCommentAreaBuilder;
import org.jxls.common.CellRef;
import org.jxls.common.Context;
import org.jxls.jdbc.JdbcHelper;
import org.jxls.transform.Transformer;
import org.jxls.transform.poi.PoiTransformer;
import org.jxls.util.JxlsHelper;

public class MavenTest {

    public static void main(String[] args) {

        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:sqlserver://ip;databaseName=reportserver", "user",
                    "pwd");
            JdbcHelper jdbcHelper = new JdbcHelper(conn);

            InputStream is = null;
            OutputStream os = null;

            is = new FileInputStream(new File("rsuser.xlsx"));
            os = new FileOutputStream("output_rsuser.xlsx");

            Context context = new Context();

            context.putVar("conn", conn);
            context.putVar("jdbc", jdbcHelper);

//          JxlsHelper.getInstance().processTemplate(is, os, context);

            Workbook workbook = WorkbookFactory.create(is);
            Transformer transformer = PoiTransformer.createSxssfTransformer(workbook, 5, false);
            AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
            List<Area> xlsAreaList = areaBuilder.build();
            for (Area xlsArea: xlsAreaList) {
                xlsArea.applyAt(new CellRef(xlsArea.getStartCellRef().getCellName()), context);
            }
            context.getConfig().setIsFormulaProcessingRequired(false); // with SXSSF you cannot use normal formula processing
            workbook.setForceFormulaRecalculation(true);
            workbook.setActiveSheet(1);
            ((PoiTransformer) transformer).getWorkbook().write(os);

            is.close();
            os.flush();
            os.close();
            System.out.println("output created.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

The template attached.

We tried with jxls 2.7.2 and 2.8.1, both same behavior.

[rsuser.xlsx](https://github.com/jxlsteam/jxls/files/4729869/rsuser.xlsx)

**Comment by SoltauFintel** [comment]
Why `workbook.setActiveSheet(1);`? It's 0 based. Why do you use it?

Strange errors? Call 'Clean project' in your Eclipse.

`os.flush()` is not necessary.

`SXSSFWorkbook->dispose()` must be called.

`context.getConfig().setIsFormulaProcessingRequired(false);` must be set earlier. Maybe that is causing your problem.

Start with a new JXLS Streaming project, setting less options - to learn how to use it. E.g. use 100 instead of 5 (or the default method with the default values). Uploading a database-based example does not help because I can't run it.

**Comment by eduardo-rs** [comment]
Hi @SoltauFintel ,

thanks for your answers. I refactored the sample to work with this: https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/stress/SxssfDemo.java

I use this method: simpleSxssf()

Here, you see the following:

    Area xlsArea = xlsAreaList.get(0);

which of course will only process the first xlsAreaList found. So I change the method to this:

```
Workbook workbook = WorkbookFactory.create(is);
                PoiTransformer transformer = PoiTransformer.createSxssfTransformer(workbook, 5, false);
                AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
                List<Area> xlsAreaList = areaBuilder.build();
                Context context = new Context();
                context.putVar("cellRefUpdater", new CellRefUpdater());
                context.putVar("employees", employees);
                for (Area xlsArea: xlsAreaList) {
                	   xlsArea.applyAt(new CellRef("Result!A1"), context);
                }
                
                context.getConfig().setIsFormulaProcessingRequired(false); // with SXSSF you cannot use normal formula
                                                                           // processing
                workbook.setForceFormulaRecalculation(true);
                workbook.setActiveSheet(1);
                transformer.getWorkbook().write(os);
```

I only put the xlsArea.applyAt in a loop and move the context.putVar up. Everything else is exact as the sample.

It works. But as I mentioned at the beginning of this thread, if I now change: 

    xlsArea.applyAt(new CellRef("Result!A1"), context);

to

    xlsArea.applyAt(new CellRef(xlsArea.getStartCellRef().getCellName()), context); 

in order to make this more generic, I get:

> Exception in thread "main" java.lang.IllegalArgumentException: Sheet index (1) is out of range (0..0)
> 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1470)
> 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.setActiveSheet(XSSFWorkbook.java:1449)
> 	at maventest.SxssfDemo.simpleSxssf(SxssfDemo.java:64)
> 	at maventest.SxssfDemo.main(SxssfDemo.java:40)
> 

Regarding your questions:

> Why workbook.setActiveSheet(1);? It's 0 based. Why do you use it?
please check the  example above. It selects the 1 sheet, which is the "result" sheet

> os.flush() is not necessary.
in my new example which bases on the jxls examples I changed this, thanks

> SXSSFWorkbook->dispose() must be called.
same as above

> context.getConfig().setIsFormulaProcessingRequired(false); must be set earlier. Maybe that is causing your problem.
as my example is now based on the jxls example, it appears in the same place it appears in the example

> Start with a new JXLS Streaming project, setting less options - to learn how to use it. E.g. use 100 instead of 5 (or the default method with the default values). Uploading a database-based example does not help because I can't run it.
I am using the same options as with the jxls example

**Comment by bonivan** [comment]
So by default Excel file with template has only one sheet "Template" which index is 0.
When you use 
`new CellRef("Result!A1")`
second sheet with name "Result" is created that is why `workbook.setActiveSheet(1);` works.
But when you use `new CellRef(xlsArea.getStartCellRef().getCellName())` it doesn't create second sheet since xlsArea object has sheet as "Template"
Because of that processed workbook has only one sheet and `workbook.setActiveSheet(1);` fails.

**Comment by eduardo-rs** [comment]
Hi bonivan,

thanks for your answer. This creates the result in a new sheet with name "MySheet". 

How to use the exact name the original sheet has ?

I am just trying to have an equivalent functionality as with 
    
    JxlsHelper.getInstance().processTemplate(is, os, context);

in which the exact name of the original sheet is used for the result sheet.

**Comment by eduardo-rs** [comment]
I will close this ticket, as the original question: "why am I getting the exception" was answered, thanks! The other question "how to use the original name" will be posted here:  https://github.com/jxlsteam/jxls/issues/39
