### ISSUE TITLE
Streaming problems

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#34]
Hi,

as mentioned in other issues, we are trying to support streaming. Our current approach replaces this:

    JxlsHelper.getInstance().processTemplate(is, os, context);

by this:

```
Workbook workbook = WorkbookFactory.create(is);
Transformer transformer = PoiTransformer.createSxssfTransformer(workbook, 5, false);
AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
List<Area> xlsAreaList = areaBuilder.build();
for (Area xlsArea: xlsAreaList) {
   xlsArea.applyAt(new CellRef("Result!A1"), context);
}
            
            
context.getConfig().setIsFormulaProcessingRequired(false); // with SXSSF you cannot use normal formula processing
workbook.setForceFormulaRecalculation(true);
workbook.setActiveSheet(1);
            
List<String> templateSheetsName = new ArrayList<>();
for (Area xlsArea : xlsAreaList) {
   templateSheetsName.add(xlsArea.getAreaRef().getSheetName());
}
            
for (String sheetName : templateSheetsName) {
    transformer.deleteSheet(sheetName);
}
            
((PoiTransformer) transformer).getWorkbook().write(os);
```

It doesn't throw any errors, but the result is not the expected result (comparing it with the result of the .processTemplate approach.

In particular, "TEST BEFORE" disappears, and the sum is not correctly set. I understand that with streaming no formulas are being evaluated, but they should be evaluated correctly afterwards with workbook.setForceFormulaRecalculation(true);, or am I wrong ?

To compare both results: output_rsuser_1.xlsx with the .processTemplate approach, _2 with the streaming approach. in _1 you see: =SUMME(D2:D37), which is correct, but in _2 you see: =SUMME(D2) which is not correct.
Also, you see in _2 that  "TEST BEFORE" disappears.

Am I doing something wrong or is this a bug ?

[rsuser.xlsx](https://github.com/jxlsteam/jxls/files/4730256/rsuser.xlsx)
[output_rsuser_1.xlsx](https://github.com/jxlsteam/jxls/files/4730253/output_rsuser_1.xlsx)
[output_rsuser_2.xlsx](https://github.com/jxlsteam/jxls/files/4730254/output_rsuser_2.xlsx)

I tested with 2.8.1.

Regards,
Eduardo

**Comment by SoltauFintel** [comment]
I'm not 100% sure, but this is not a bug. You can't do such a calculation using JXLS Streaming. JXLS in streaming mode cannot expand the sum area. The last row is processed as last row. Streaming is used for putting many stupid rows to one sheet. It might be possible to do a (1-row-) calculation in column C with values from columns A+B.

Please have a look at SelectSheetsForStreamingPoiTransformer. In our company we usually have one sheet with many rows as data input and the other sheets for using these data rows and doing calculations. One sheet (or 2) with streaming, the other sheets with no streaming.

The order of the sheets can be important for Excel file creation speed. But I can't tell you any details.

JXLS Streaming definitely works with the max number of rows (1 million).

"TEST BEFORE disappears" -> Please put jx:area in A1.

**Comment by eduardo-rs** [comment]
Hi @SoltauFintel ,

I understand that formulas cannot be calculated by streaming. But then I don't understand why in the jxls example: https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/stress/SxssfDemo.java 
method:  simpleSxssf()  , you can see:
    context.getConfig().setIsFormulaProcessingRequired(false);
    workbook.setForceFormulaRecalculation(true);

If I understand these two lines correctly, they deactivate jxls formula processing and activate excel formula recalculation. So when opening excel, the formulas will be calculated. This seems to work for the simple case you mention here:

> It might be possible to do a (1-row-) calculation in column C with values from columns A+B.

this is the case in the jxls example, pls check the formula set here: =C4*(1+D4) (in row 4)

If I try to add a "total sum" of the values =SUMME(E4), this doesn't work, as the formula is not expanded correctly. The formula is in the result: =SUMME(E4) which of course is not correct. 

Is there any way of expanding this formula correctly and leaving calculation to excel with workbook.setForceFormulaRecalculation(true);  ? I tried with:

    jx:updateCell(lastCell="E4"  updater="cellRefUpdater")

but this didn't work. 

I will take a look also at the SelectSheetsForStreamingPoiTransformer you mention.

**Comment by eduardo-rs** [comment]
Regarding the "TEST BEFORE": 

> "TEST BEFORE disappears" -> Please put jx:area in A1.

Yes, of course I could do this, but this will impose jx:area to always start in A1, which is not the case in the normal case. 

If I change the jxls example to:

```
Context context = new Context();
context.putVar("cellRefUpdater", new CellRefUpdater());
context.putVar("employees", employees);
JxlsHelper.getInstance().processTemplate(is, os, context);
```

and adapt the template, then the "TEST BEFORE" does not disappear, even if the jx:area is not put in A1.

If I leave the simpleSxssf() as in the original jxls example, the "TEST BEFORE" disappears.

**Comment by eduardo-rs** [comment]
This worked with this code: https://github.com/jxlsteam/jxls/issues/39
