### ISSUE TITLE
Samples not being found

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#35]
Hi,

here:
https://bitbucket.org/leonate/jxls-demo/src/master/ I read:

!!!Jxls-2 Examples - DEPRECATED!!!
DEPRECATION NOTE!
All the examples have been migrated to the [main Jxls repo](https://bitbucket.org/leonate/jxls/src/master/jxls-examples/).

The link points to: https://bitbucket.org/leonate/jxls/src/master/jxls-examples/
where I can read:

Hmm... can't find that one That file or directory doesn’t exist. Go back to the previous page and try another one.

What is the correct link of the examples?

**Comment by SoltauFintel** [comment]
Use "Find file" function on this github repo and type in "example".
