### ISSUE TITLE
Streaming parameters question

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#36]
Hi,

what is the meaning of the 3 last parameters of createSxssfTransformer ?
In the javadoc: http://jxls.sourceforge.net/javadoc/jxls-poi/org/jxls/transform/poi/PoiTransformer.html#createSxssfTransformer-org.apache.poi.ss.usermodel.Workbook-int-boolean-boolean-

I only see:

createSxssfTransformer

> public static PoiTransformer createSxssfTransformer(org.apache.poi.ss.usermodel.Workbook workbook,
> int rowAccessWindowSize,
> boolean compressTmpFiles,
> boolean useSharedStringsTable)
> Creates transformer for given workbook and streaming parameters. Streaming will be used.
> Parameters:
> workbook - Excel template. Format must be XLSX.
> rowAccessWindowSize -
> compressTmpFiles -
> useSharedStringsTable -
> Returns:
> transformer instance with the given workbook as template

would it be possible to explain / document these 3 parameters? 

Thanks

**Comment by eduardo-rs** [comment]
I found out some information:

rowAccessWindowSize: https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/streaming/SXSSFWorkbook.html#DEFAULT_WINDOW_SIZE
Specifies how many rows can be accessed at most via SXSSFSheet.getRow(int). When a new node is created via SXSSFSheet.createRow(int) and the total number of unflushed records would exceed the specified value, then the row with the lowest index value is flushed and cannot be accessed via SXSSFSheet.getRow(int) anymore.

compressTmpFiles:
https://poi.apache.org/apidocs/4.0/org/apache/poi/xssf/streaming/SXSSFWorkbook.html#SXSSFWorkbook-org.apache.poi.xssf.usermodel.XSSFWorkbook-int-boolean-boolean-

whether to use gzip compression for temporary files

useSharedStringsTable
https://poi.apache.org/apidocs/4.0/org/apache/poi/xssf/streaming/SXSSFWorkbook.html#SXSSFWorkbook-org.apache.poi.xssf.usermodel.XSSFWorkbook-int-boolean-boolean-

whether to use a shared strings table

Some more information on shared strings table: https://stackoverflow.com/questions/47851078/why-does-sxssf-workbook-apache-poi-create-larger-xlsx-sizes-than-excel

I would suggest to include the information on the parameters in the documentation, or a link to the POI documentation

**Comment by SoltauFintel** [comment]
No action by eduardo-rs -> ticket closed
