### ISSUE TITLE
Image after each command was stretched

### ISSUE THREAD

**Issue by tim55355** [jxlsteam/jxls#41]
I try to add a picture below each command like :
jx:image(lastCell="H18" src="signature" imageType="PNG" scaleX="1.7976931348623157E308" scaleY="1.7976931348623157E308")
I want the picture to be the original size,but  it was stretched.What's the reason...

**Comment by SoltauFintel** [comment]
Please provide an example as a pull request. Otherwise ticket will be closed on 2020-06-28.

http://jxls.sourceforge.net/source_code.html
