### ISSUE TITLE
Jxls template with static columns after dynamic columns

### ISSUE THREAD

**Issue by nguacon90** [jxlsteam/jxls#45]
Dear jxls team,
I try rendering (static columns)(dynamic columns)(static columns). However, right static columns have not fill data exactly index, index has not been updated after appending dynamic columns. 
For example: Result after rendering:
A | B | C | D
1  | 2 | 0 | 3
A: static column with value 1,
B,C: dynamic columns with values: 2, 3
D: static column with value 0.
Expected values filled: 1 | 2 | 3 | 0.

Can you show me any way to rendering correctly? 
Thank you very much.

**Comment by SoltauFintel** [comment]
Are you looking for jx:each in cell B with parameters direction=right and lastCell=B ? With 2 items in the list 2 dynamic columns would be created. The value in column C should be moved to column D.

Would be helpful if you add your template XLSX, your actual result file and your expected result file. And JXLS code.

**Comment by nguacon90** [comment]
Thank @SoltauFintel. This works perfectly.
