### ISSUE TITLE
Dependent Queries in jxls2

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#47]
Hi,

I am trying to use dependent queries with jxls2 as in http://jxls.sourceforge.net/1.x/samples/reportsample.html, Dependent Queries

The example uses jxls1 syntax so I translate it to jxls2 syntax. 

So I translate the following:
(jxls1)
<jx:forEach items="${rm.exec('SELECT name, payment, bonus FROM employee e where e.depid = ' + dep.id)}" var="employee">

to jxls2: 
jx:each(items="jdbc.query('SELECT name, payment, bonus FROM employee e where e.depid = ' + dep.id)" var="employee" lastCell="B3")

and everything works as expected. So dependent queries work with this syntax. 

But if I change this:
jx:each(items="jdbc.query('SELECT name, payment, bonus FROM employee e where e.depid = ' + dep.id)" var="employee" lastCell="B3")

to this:
jx:each(items="jdbc.query('SELECT name, payment, bonus FROM employee e where e.depid = ?', dep.id)" var="employee" lastCell="B3")

no data is being printed. Are jxs2 dependent queries not supporting the "?" syntax for parameters ?

Regards,
Eduardo

**Comment by SoltauFintel** [comment]
Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.

**Comment by leonate** [comment]
The parameterized queries should work. Check out the https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/SqlDemo.java and https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/resources/org/jxls/examples/SqlDemo.xls and see if that example works for you.
Maybe try to debug your code to see if there is any issue with `JdbcHelper ` class. In that you can always use your own class to fetch the data or submit a patch.
If the above does not help, submit a simple test demonstrating the issue (as described in https://github.com/jxlsteam/jxls/blob/master/CONTRIBUTING.md) and we can take a look.
