### ISSUE TITLE
How to load a Jxls template from external URL?

### ISSUE THREAD

**Issue by DarshitaPadaria** [jxlsteam/jxls#48]
Hi,

We are using Jxls to generate excel exports. It works fine and exports are generated for templates read from file system. However we have a need to keep them on central location and read the templates from URL. Does Jxls support templates from URL? 

Exception details:
java.io.IOException: **Your InputStream was neither an OLE2 stream, nor an OOXML stream**
	org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:234)
	org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:198)
	org.jxls.transform.poi.PoiTransformer.createTransformer(PoiTransformer.java:135)
	org.jxls.transform.poi.PoiTransformer.createTransformer(PoiTransformer.java:120)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:497)
	org.jxls.util.TransformerFactory.createTransformer(TransformerFactory.java:43)
	org.jxls.util.JxlsHelper.createTransformer(JxlsHelper.java:425)
	org.jxls.util.JxlsHelper.processTemplate(JxlsHelper.java:206)

Sample Code:
			//read template content
			URL url = new URL("http://....//template.xlsx");

			final InputStream is = url.openStream();
			byte[] resultBuffer = org.apache.commons.io.IOUtils.toByteArray(is);
			
			//Update jxls model 			
			Context context = new Context();
			context.putVar(objectName, data);
			
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			//export
			JxlsHelper.getInstance().processTemplate(is, baos, context);

**Comment by SoltauFintel** [comment]
(That is now from memory. I hope I am not mistaken. Please check.)

Opening an XLSX file via the `File` constructor (instead of the `InputStream` c.) results in faster processing. It is therefore advisable to download the file as a temp file with your own source code and then process it with JXLS.

I don't know if JXLS or POI can handle a http URL.

**Comment by SoltauFintel** [comment]
http://poi.apache.org/components/spreadsheet/quick-guide.html#FileInputStream
