### ISSUE TITLE
Jxls template with dynamic columns and formula

### ISSUE THREAD

**Issue by c0nf1ck** [jxlsteam/jxls#51]
Hey everyone, i'm using this library to generate a report and having some issues with a formula in a dynamic column;

My expected result:

![expected](https://user-images.githubusercontent.com/34660211/92514146-d4506780-f1e7-11ea-89b9-e5185ee71b81.png)

My current result:

![result](https://user-images.githubusercontent.com/34660211/92514150-d4e8fe00-f1e7-11ea-82f1-9ac7b6d07826.png)

This is my [template](https://github.com/jxlsteam/jxls/files/5190347/template.xlsx), [my current result](https://github.com/jxlsteam/jxls/files/5190365/result.xlsx) and  [my expected result](https://github.com/jxlsteam/jxls/files/5190369/expected.xlsx)

Anyone can help? Thank you

**Comment by SoltauFintel** [comment]
just a guess:

cell B7

jx:each(items="triage.equipmentList" var="e" lastCell="H7")

try lastCell G7

**Comment by SoltauFintel** [comment]
It also looks like a Excel PivotTable. JXLS supports that.

**Comment by c0nf1ck** [comment]
@SoltauFintel thank you for the reply,

if i put lastCell to G7 at cell B7 the formula at J7 gets redundancy error.

And i can't move to pivot (even being a better solution)

**Comment by c0nf1ck** [comment]
I know that it's not a good solution, but for now i did like this:

``` java
List < String > formulas = new ArrayList < String > ();

char letter = 'G';
for (int index = 0; index < dates.size(); index++) {
  if (index > 0) letter++;

  formulas.add(String.format("%s7:%s%d", letter, letter, 6 + equipmentList().size()));
}

params.put("formulas", formulas);
```

And at template:

`
$[SUM(${f})]
`

**Comment by SoltauFintel** [comment]
@leonate  - Please look at branch feature-51. Do you know a solution for the template or is it a bug?

**Comment by leonate** [comment]
I have modified the template to specify taking the cell references only by columns with `jx:params(formulaStrategy="BY_COLUMN")` in the formula cell and now the test is green.

![image](https://user-images.githubusercontent.com/697298/93718599-a3741900-fb7d-11ea-82eb-f93392f38461.png)

**Comment by SoltauFintel** [comment]
@c0nf1ck  - Did that solves your problem?

**Comment by c0nf1ck** [comment]
Yes, that solves my problem. Thank you @SoltauFintel and @leonate
