### ISSUE TITLE
Can't parse  Jxls template  $[=SUM(F:F)]    

### ISSUE THREAD

**Issue by TanqiZhou** [jxlsteam/jxls#55]
Can't parse  Jxls template  $[=SUM(F:F)] ，Need to click  Out $[=SUM(F:F)]  Normal Show.

**Comment by SoltauFintel** [comment]
Please add template XLSX, result file and expected file.

**Comment by TanqiZhou** [comment]
[input-1.xlsx](https://github.com/jxlsteam/jxls/files/5253099/input-1.xlsx)
[input-2.xlsx](https://github.com/jxlsteam/jxls/files/5253100/input-2.xlsx)
[result .xlsx](https://github.com/jxlsteam/jxls/files/5253101/result.xlsx)
[expected .xlsx](https://github.com/jxlsteam/jxls/files/5253104/expected.xlsx)

**Comment by TanqiZhou** [comment]
Bug appears in the last line of the result sum function.

**Comment by TanqiZhou** [comment]
.putVar("sum", "=SUM(F:F)")    is  input-1.xlsx  operation...

**Comment by SoltauFintel** [comment]
Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.

**Comment by edu-de** [comment]
Hi @TanqiZhou ,

I would recommend you to delete everything unnecessary from the template, so you have a minimal example template where the issue occurs. With a minimal example it would be much easier to reproduce and maybe correct the problem.
You can see an example of what I mean with "minimal example" here:

https://github.com/jxlsteam/jxls/issues/72
