### ISSUE TITLE
Updating row heights on template with multiple areas (using applyAt)

### ISSUE THREAD

**Issue by jools-uk** [jxlsteam/jxls#57]
Given a template with multiple jx:area defined, one after the other, with a static top region for each area, and when using xlsArea.applyAt() to transform the areas, updateRowHeights does not correctly copy the height from the source cell. It seems to attempt to lookup the transformed location in the source area and will not find a hit if rows/cols have been added to a prior area. I suspect issue is srcRow, which is not looking at the real source.

```java
XlsArea.java
    private void updateRowHeights(CellRef areaStartCellRef, int relativeStartRow, int relativeEndRow) {
        if (transformer == null) return;
        for (int relativeSrcRow = relativeStartRow; relativeSrcRow <= relativeEndRow; relativeSrcRow++) {
            if (!cellRange.containsCommandsInRow(relativeSrcRow)) {
                int relativeTargetRow = cellRange.findTargetRow(relativeSrcRow);
                int targetRow = areaStartCellRef.getRow() + relativeTargetRow;
//use this.startCellRef instead?
                int srcRow = areaStartCellRef.getRow() + relativeSrcRow;
                try {
                    transformer.updateRowHeight(startCellRef.getSheetName(), srcRow, areaStartCellRef.getSheetName(), targetRow);
                } catch (Exception e) {
                    logger.error("Failed to update row height for src row={} and target row={}", relativeSrcRow, targetRow, e);
                }
            }
        }
    }
```

**Comment by SoltauFintel** [comment]
Please add template XLSX, result file and expected file. A test case including Excel files as pull request would be best. If we change something, we need a test case for it.

Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.
