### ISSUE TITLE
jx each direction right clones in down direction

### ISSUE THREAD

**Issue by WayfarerHungaryElite** [jxlsteam/jxls#61]
I have an excel template with a cell at D1 with the following comment
`jx:each(items="context.numberslist" var="number" lastCell="D1" direction="RIGHT")`

This is part of an area defined at A1 cell by the following comment:
`jx:area(lastCell="D8")`

There are also a few vertical foreach comments on the A column, like this:
`jx:each(items="context.list" var="variable" lastCell="C4")`

The relevant code in my project is:

```
InputStream is = MyClass.class.getResourceAsStream(templateResource + language.toUpperCase() + ".xlsx");

ByteArrayOutputStream os = new ByteArrayOutputStream();
Transformer transformer = TransformerFactory.createTransformer(is, os);
AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
Context context = transformer.createInitialContext();
context.putVar("context", sheetContext);
for (Area xlsArea : areaBuilder.build()) {
    xlsArea.applyAt(xlsArea.getStartCellRef(), context);
}
transformer.write();
is.close();
os.flush();
```

The vertical clones work as expected. However, the horizontal one does not. It instead clones vertically, even though the direction was specified. How do I make it work?

[actual.xlsx](https://github.com/jxlsteam/jxls/files/5378007/actual.xlsx)
[expected.xlsx](https://github.com/jxlsteam/jxls/files/5378008/expected.xlsx)
[template.xlsx](https://github.com/jxlsteam/jxls/files/5378009/template.xlsx)

**Comment by SoltauFintel** [comment]
I am not aware of any bug in the library and there is probably a testcase for it.

Which version are you working with?

It would be helpful if you could upload the XLSX template here. The actual output and expected output would be good too.

Maybe the area of jx:area(lastCell="D8") needs to be increased?

**Comment by WayfarerHungaryElite** [comment]
updated initial comment with xls files

jxl is version 2.2.3
jxls-poi is 1.0.5

**Comment by SoltauFintel** [comment]
You're using a fairly old version. Please test it with the latest released version. It may well be that there was a bug in 2.2.x that has long been fixed.

**Comment by WayfarerHungaryElite** [comment]
Updated and it now works as expected. Thank you.
