### ISSUE TITLE
Don't read iterable ahead of time

### ISSUE THREAD

**Issue by fabianMendez** [jxlsteam/jxls#64]
Hello,

As I mentioned in another issue I was trying to generate a report with quite a lot of rows coming from an SQL database.

I tried to optimize the memory usage by creating an Iterable backed by the resultset (which does not fetch all the rows at once), but right after returning the iterable it is used to create a List with all its elements, this is the code:

https://github.com/jxlsteam/jxls/blob/90b354661e2add24fc7c18d6ff11189f776e851f/jxls/src/main/java/org/jxls/util/Util.java#L585-L599

And looking at the commit history it does not seem to be a very strong reason for this (just avoiding warnings).

I changed the code to this, ran all the tests and all of them passed, so I think it's safe to change it:
```java
@SupressWarnings("unchecked")
Iterable<Object> ret = (Iterable<Object>) collectionObject;

return ret;
```

What do you think?

**Comment by SoltauFintel** [comment]
You're right. Thank you.
