### ISSUE TITLE
JXLS Losing rows when using jx:if is false

### ISSUE THREAD

**Issue by holoc285** [jxlsteam/jxls#66]
Can you help me?

**Comment by SoltauFintel** [comment]
You have given a little bit of information (missing template.xlsx).

Maybe you missed the areas part. See this example: https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/resources/org/jxls/templatebasedtests/If01Test.xlsx

**Comment by holoc285** [comment]
I missed the areas part. Thank you so much
