### ISSUE TITLE
Unwanted Textbox in MS Excel

### ISSUE THREAD

**Issue by icrnjak** [jxlsteam/jxls#67]
Jxls and jxls-poi version: 

- 2.8.1

Office vendor and version: 

- OpenOffice 4.1.5  - OK
- LibreOffice 7.0.1.2 - OK
- **MS Office 2007 and 2016 - Not OK - Textbox is present**

Excel version:

- Textbox only appears with .xlsx files. There is no textbox when using .xls files

Java (11) code used:

```java
public void export() {
    try (InputStream is = Exporter.class.getResourceAsStream("/shop-items-template.xlsx")) {
        Path path = Paths.get("shop-items.xlsx");
        if (!Files.exists(path)) {
            Files.createFile(path);
        }
        File file = path.toFile();
        try (OutputStream os = new FileOutputStream(file)) {
            Context context = configureContext();
            JxlsHelper.getInstance().processTemplate(is, os, context);
        }
    } catch (IOException e) {
        // Handle it
    }
}

private Context configureContext() {
    Context context = new Context();
    context.putVar("shop", shopRepository.findById(1).orElseThrow());
    context.putVar("items", itemRepository.findAll());
    return context;
}  
```

## Minimal use case
jx:each inside a jx:area, but jx:each and jx:area do not originate from the same comment/cell.
### Template
[shop-items-template-minimal.xlsx](https://github.com/jxlsteam/jxls/files/5457362/shop-items-template-minimal.xlsx)
![shop-items-minimal-template](https://user-images.githubusercontent.com/32704201/97549543-cee5f100-19d0-11eb-8c5b-a3f073242fd5.jpg)
### Result
[shop-items-minimal.xlsx](https://github.com/jxlsteam/jxls/files/5457315/shop-items-minimal.xlsx)
#### LibreOffice Calc
This is what it looks like in LibreOffice and OpenOffice Calc and what I believe it should like like in other Excel programs
![shop-items-minimal-expected-libre](https://user-images.githubusercontent.com/32704201/97550160-972b7900-19d1-11eb-985f-d0caa849d411.jpg)
####  MS Excel 2007
There is a massive TextBox element covering data on the Sheet, but when you delete the textbox, results are fine.
![shop-items-minimal-ms-excel](https://user-images.githubusercontent.com/32704201/97550979-ac54d780-19d2-11eb-9631-a5245cf3cdbd.jpg)

In my real use case I have some other cells to process in jx:area and display a jx:each below said cells. Result is the same and TextBox is present only when viewing the generated .xlsx file in MS Excel.
I can provide more info if needed.

**Comment by SoltauFintel** [comment]
Does the error also occur if you create the template from scratch with MS Excel?

**Comment by icrnjak** [comment]
Looks like there is no Textbox in the generated xlsx file if I use MS Excel to create the template. I forgot how incompatible LibreOffice and MS Office can be.

**Comment by SoltauFintel** [comment]
I strictly recommend using only MS Excel for editing templates. Office 365 is the best. I recommend also the XLSX format.

Of course, it would also be good if all users used Office 365. But you can't force that.
