### ISSUE TITLE
Each command within Each command

### ISSUE THREAD

**Issue by WayfarerHungaryElite** [jxlsteam/jxls#69]
Hello

I would like to find the way I can have a row that is copied downwards, but that row has a dynamic amount of columns at the end of it. I think there is a way with double jx:each command, but I do not know the correct syntax. Can you help me?

Data-wise in JAVA, it would be a POJO with some fields, and a List containing a different POJO with only one field (OR a List containing a primitive type).

[expected2.xlsx](https://github.com/jxlsteam/jxls/files/5464956/expected2.xlsx)
[template2.xlsx](https://github.com/jxlsteam/jxls/files/5464957/template2.xlsx)

**Comment by SoltauFintel** [comment]
short answer

jx:each(items="list", var="A", lastCell="...")

and within this area:

jx:each(items="**A.**sublist", var="B", lastCell="...")

**Comment by WayfarerHungaryElite** [comment]
Could you update my template please? Without a proper example, it is not easy to understand for me. I am not sure which variable names I need to use in the template and which to use in my POJOs.

**Comment by SoltauFintel** [comment]
Sorry, no time.

Please clone jxls and (for example) have a look at NestedSumsTest.java, NestedSumsTest.xlsx.
