### ISSUE TITLE
Exceptions not propagated  in EachCommand

### ISSUE THREAD

**Issue by deicon** [jxlsteam/jxls#73]
Exceptions during the evaluation of commands are catched and silently return empty collections. Callers are not able to retrieve the actual cause but are only able to see the Error Message in Std.Err. 

Exceptions like this will cause the Report to be invalid hence the Exception should propagate up to the caller. 

In EachCommand.java
```
 @Override
    public Size applyAt(CellRef cellRef, Context context) {
        Iterable<?> itemsCollection = null;
        try {
            itemsCollection = util.transformToIterableObject(getTransformationConfig().getExpressionEvaluator(), items, context);
            orderCollection(itemsCollection);
        } catch (Exception e) {
            logger.warn("Failed to evaluate collection expression {}", items, e);
            itemsCollection = Collections.emptyList();
        }
        Size size;
        if (groupBy == null || groupBy.length() == 0) {
            size = processCollection(context, itemsCollection, cellRef, var);
        } else {
            Collection<GroupData> groupedData = util.groupIterable(itemsCollection, groupBy, groupOrder);
            String groupVar = var != null ? var : GROUP_DATA_KEY;
            size = processCollection(context, groupedData, cellRef, groupVar);
        }
        if (direction == Direction.DOWN) {
            getTransformer().adjustTableSize(cellRef, size);
        }
        return size;
    }
```

**Comment by SoltauFintel** [comment]
A known problem. There are other places too. Exchanging classes probably also needs to be simplified. This is planned for the next major release 3. 3.0 should come after 2.9. However, we are working little on JXLS (because of Corona). So this will take time.

My tip can only be to look at the console after report changes.

**Comment by SoltauFintel** [comment]
My strategy would be to write a decorator class for the SLF4J Logger class. And then to catch the warn (or error) message and throw an exception. However, I don't know how to install the decorated logger.

**Comment by deicon** [comment]
What's about propagating Exceptions and let the Report Fail with Exception ? 
This way the caller will be able to react on failed Reports and possibly see the actual error message within the Exception. Printing an Error on the console will not help, when the report is used in any kind of backen server.

**Comment by leonate** [comment]
We can propagate exceptions but perhaps we should make them configurable? E.g. if there are some bad data that someone prefers to ignore, then propagating exceptions can break the current behavior.

**Comment by SoltauFintel** [comment]
deicon, we shouldn't break the current behavior. Therefore my idea is to optionally add throw-exception-behavior - in the logger. But I don't know how to install a decorated slf4j Logger class. If this would not be possible (what I cannot believe) we could change jxls (with default behavior like current behavior).

**Comment by SoltauFintel** [comment]
@leonate My plan is to solve this problem. I don't know to do it with a Logger decorator, so I'll try something else...

**Comment by SoltauFintel** [comment]
@deicon Please have a look at my PR #171. Is that change ok for you?
