### ISSUE TITLE
util hyperlink broken after update

### ISSUE THREAD

**Issue by WayfarerHungaryElite** [jxlsteam/jxls#74]
I updated the jxls and jxls-poi in my project as
jxls 2.2.3 -> 2.8.1
jxls-poi  1.0.5 -> 2.8.1

${util.hyperlink(address, title)}

I had several of this hyperlink in one of my templates, and they are no longer replaced, they are completely empty. The other variable replacements are working fine. I cannot find any documentation stating if it was changed, I cannot even find documentation that this is even a feature (only stackoverflow questions). Can somebody check if there is really a bug or just something changed? Thanks.

[actual.xlsx](https://github.com/jxlsteam/jxls/files/5510185/actual.xlsx)
[expected.xlsx](https://github.com/jxlsteam/jxls/files/5510186/expected.xlsx)
[template.xlsx](https://github.com/jxlsteam/jxls/files/5510187/template.xlsx)

**Comment by SoltauFintel** [comment]
I don't know if there was a change or a bug. Works with master. Please try version 2.9.0.

You could also check the content of Context. Is "util" in it?
And you could set a breakpoint on org.jxls.transform.poi.PoiUtil.hyperlink(String, String)

**Comment by WayfarerHungaryElite** [comment]
Updated to 2.9.0, no change. Perhaps it relies on a dependency?
I still haven't found any documentation about util.hyperlink. Is there any?
"util" is not in context. I was under the impression util is a built-in feature of jxls that in this case is responsible for creating hyperlinks.
It does not stop in the breakpoint after updating, but it did before updating. Relevant code:

Transformer transformer = TransformerFactory.createTransformer(is, os);
AreaBuilder areaBuilder = new XlsCommentAreaBuilder(transformer);
Context context = new Context(); //transformer.createInitialContext(); - used to be this, perhaps this is a clue?
context.putVar("context", sheetContext);
for (Area xlsArea : areaBuilder.build()) {
    xlsArea.applyAt(xlsArea.getStartCellRef(), context);
}

**Comment by SoltauFintel** [comment]
You answered the question yourself. Then can we close the ticket?

**Comment by WayfarerHungaryElite** [comment]
How did I answer it?

**Comment by WayfarerHungaryElite** [comment]
It seems the old jxls jar had a manually added method that had the " context.putVar(POI_CONTEXT_KEY, new PoiUtil());" line in it. Adding that to context makes it work again.
