### ISSUE TITLE
Python extension?

### ISSUE THREAD

**Issue by Deninc** [jxlsteam/jxls#76]
While searching for a way to use jxls in Python, I found this article from 2019:
https://hugoworld.wordpress.com/2019/01/21/easy-excel-reporting-with-python-and-jinja2/

The project seems discontinued and I couldn't find the author contact information. I wonder is the author also someone from the jxlsteam? 

Is there any port of jxls for Python user?

**Comment by leonate** [comment]
> I wonder is the author also someone from the jxlsteam?
Not really.
> Is there any port of jxls for Python user?
I am not aware about any Python port of jxls.
Jxls heavily relies on Apache POI, so to make a port one should have a similar library accessible in Python. I found https://pypi.org/project/poi/ , but it does not look like a mature a project.
Maybe you can utilise Jython, which I guess should have an access to Java libraries and use jxls from it?

**Comment by Deninc** [comment]
@leonate thank you for the quick answer.
Maybe having this tool as binary and being able to run on command line is a good idea? 
But that will be for another time I guess.
