### ISSUE TITLE
Multi-line and comment support question

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#79]
Hi,

I saw here: https://bitbucket.org/leonate/jxls/pull-requests/30/new-manual-command-parser-with-multi-line/diff
a limitation on sql query in JXLS reports: the query cannot contain new lines or comments.

We are also having problems with multi-line sql statements. I tested this with JXLS 2.9.0 and multi-line statements do not work there. As I see that this pull request was being declined, I wanted to ask if it is planned to support multi-line sql statements in the future? 

We can look into this as well / work on this if no other current pull requests are open for this, can you pls confirm so we can open a pull request and start working on this ?

Regards,
Eduardo

**Comment by SoltauFintel** [comment]
You can work on this.

**Comment by eduardo-rs** [comment]
Hi @SoltauFintel 
thanks, we will take a look in January at this. We already identified the place where this has to be changed and will work on a solution. We will let you know.

**Comment by SoltauFintel** [comment]
Who is alexlust? Same user/company as eduardo-rs?

**Comment by eduardo-rs** [comment]
Hi @SoltauFintel 

yes, same company, @alexlust is a colleague who worked on this issue

**Comment by SoltauFintel** [comment]
hi @alexlust 
please have a look in bug #111 . Can you fix it soon or shall we revert your feature to give you more time to stabilize the feature?

Please respond in #111 

Your changes should be based on branch feature-111 (please see #112)

**Comment by SoltauFintel** [comment]
This feature must be activated before use:

`XlsCommentAreaBuilder.MULTI_LINE_SQL_FEATURE = true;`
