### ISSUE TITLE
when i use each command, Empty List will lead row shift ，this will lead a empty row in the area end

### ISSUE THREAD

**Issue by CrackerGit** [jxlsteam/jxls#80]
version :2.9.0
this is my template file .
![image](https://user-images.githubusercontent.com/44165444/102869825-25265c00-4477-11eb-9759-c4824c074346.png)

**Comment by CrackerGit** [comment]
may i have some method to handle

**Comment by SoltauFintel** [comment]
please add screenshots (also with row numbers): template, result, expectation

Which Microsoft Excel version has been used for creating the template?

my advice: recreate the template file from scratch with Excel

**Comment by SoltauFintel** [comment]
no response -> ticket closed
