### ISSUE TITLE
Is that sure the problem B160 has been fixed?

### ISSUE THREAD

**Issue by liaoxuewei** [jxlsteam/jxls#81]
https://stackoverflow.com/questions/36241753/sxssf-transformer-with-jxls-2#

Attempting to write a row[0] in the range [0,0] that is already written to disk.

I testing the latest version doesn't solve the problem. Is that sure 2.7.0 can solve the proble?

**Comment by liaoxuewei** [comment]
https://bitbucket.org/leonate/jxls/issues/160/jx-each-with-direction-right-with-sxssf

**Comment by SoltauFintel** [comment]
You should have a look at the release notes. http://jxls.sourceforge.net/changes.html Version 2.7.2 is the latest 2.7.x release. Please try 2.7.2.

Version 2.9.0 is the latest JXLS release.

The testcase IssueB160Test works in my master workspace.

**Comment by liaoxuewei** [comment]
Thanks for replay!
I refer to the following https://github.com/jxlsteam/jxls/issues/32 method(use SelectSheetsForStreamingPoiTransformer). The export is normal, but the header of the exported part is missing in one sheet. But other sheets are normal (not so complicated). Did I do something wrong?
![image](https://user-images.githubusercontent.com/970765/103742427-c1369280-5035-11eb-975a-2b2f8316a9a3.png)
![image](https://user-images.githubusercontent.com/970765/103742312-92b8b780-5035-11eb-889f-858d0267bf9a.png)

**Comment by liaoxuewei** [comment]
> You should have a look at the release notes. http://jxls.sourceforge.net/changes.html Version 2.7.2 is the latest 2.7.x release. Please try 2.7.2.
> 
> Version 2.9.0 is the latest JXLS release.
> 
> The testcase IssueB160Test works in my master workspace.

I can not access that URL...
I may need to try another test.

**Comment by SoltauFintel** [comment]
> > http://jxls.sourceforge.net/changes.html 

> I can not access that URL...

Strange. But you should be able to access it here: https://github.com/jxlsteam/jxls/blob/master/jxls-site/src/site/markdown/changes.md

**Comment by SoltauFintel** [comment]
I can't find a mistake in your screenshot.

It's hard to help here. I am missing further information (template, result, expectation, source code).

**Comment by liaoxuewei** [comment]
I did a simple demo to reproduce the problem. Using non sxssf mode is OK.
But there are two problems in mode of sxssf:
One is that the following columns of using direction=RUGHT are covered;
The other is, the unit:mergeCell extension function will cause the contents of the previous column header to be cleared. If there is no excel comment with unit:mergeCell, the previous column header will output normally.

[JxlsTest.zip](https://github.com/jxlsteam/jxls/files/5780149/JxlsTest.zip)

**Comment by liaoxuewei** [comment]
It seems that SXS export mode does not improve the memory consumption, why ...

**Comment by SoltauFintel** [comment]
Streaming will only work if you specify the sheet name: `streamingSheets.add("Template");`

In my company we only use streaming for very simple lists. So 1 jx:area and 1 jx:each in the whole sheet. I don't know if DIRECTION=RIGHT can be used with streaming. Streaming does not support every Excel/JXLS feature.

**Comment by liaoxuewei** [comment]
> Streaming will only work if you specify the sheet name: `streamingSheets.add("Template");`
> 
> In my company we only use streaming for very simple lists. So 1 jx:area and 1 jx:each in the whole sheet. I don't know if DIRECTION=RIGHT can be used with streaming. Streaming does not support every Excel/JXLS feature.

>>> I don't know if DIRECTION=RIGHT can be used with streaming
https://github.com/jxlsteam/jxls/issues/32
What is said here has been solved? isn't it?

Can anybody test my demo, and find out the solution? Thanks a lot...
I will also try to track the source code to see if it can be solved, but because I am not familiar with it, I may not be able to find out the problem.

From the test results, I think it must can be solved.

**Comment by liaoxuewei** [comment]
> Streaming will only work if you specify the sheet name: `streamingSheets.add("Template");`
 
I made a mistake here. I'll test it again.

**Comment by liaoxuewei** [comment]
> > Streaming will only work if you specify the sheet name: `streamingSheets.add("Template");`
> 
> I made a mistake here. I'll test it again.

            transformer = new SelectSheetsForStreamingPoiTransformer(wb);
            Set<String> streamingSheets = new HashSet<>();
==>add code
            for (int i = 0; i < wb.getNumberOfSheets(); i++) {
                streamingSheets.add(wb.getSheetName(i));
            }
==>add code
            ((SelectSheetsForStreamingPoiTransformer) transformer).setDataSheetsToUseStreaming(streamingSheets);

It's work well, but the two problems in mode of sxssf still exists.

**Comment by SoltauFintel** [comment]
> Can anybody test my demo, and find out the solution?

when we have time ...

> for (int i = 0; i < wb.getNumberOfSheets(); i++) {
> streamingSheets.add(wb.getSheetName(i));

SelectSheetsForStreamingPoiTransformer is for using streaming for a few sheets. Therefore you specify the sheet names explicitly and hard-coded. The loop over all sheet names is "wrong".

**Comment by SoltauFintel** [comment]
I studied the sources. I cannot offer a solution. Maybe someone else? I pushed the sources into the feature-81 branch.

**Comment by SoltauFintel** [comment]
Nothing more seems to be happening here. -> closed
