### ISSUE TITLE
evaluateFormulas not working as expected

### ISSUE THREAD

**Issue by Turbocube644** [jxlsteam/jxls#82]
When set to true, evaluateFormulas of JxlsHelper and Transformer evaluate the formulas before saving the Workbook.
When set to false, however, the documentation between the two differs.

JxlsHelper doesn't specify what will happen:
```
/**
 * @return true if formulas will be evaluated after the processing or false otherwise
 */
public boolean isEvaluateFormulas() { [...] }
```
The corresponding set-Function sepcifies, that the variable will be passed to the tranformer.
The Transformer however states, that Excel will reevaluate all formulas on opening (which it currently **does not**)
```
/**
 * @return false: formulas will be evaluated by MS Excel when opening the Excel file, true: evaluate formulas before writing
 */
boolean isEvaluateFormulas();
```

I suppose the behaviour of the Transformer is the wanted one?
Having a look at Apache POI we can set the flag forceFormulaRecalculation of a Workbook to tell Excel to evaluate the formulas when being opened. This flag currently is not used anywhere in Jxls.
I changed that locally, tested it and it works as expected.

If wanted I can provide a code snipped or a pull requests which either sets the flag when evaluateFormulas is false or adds another corresponding flag to JxlsHelper and Transformer (and its implementing classes). This then sets the Workbook flag accordingly.

**Comment by SoltauFintel** [comment]
Please check the Calculation options is set to automatic in your template:

![image](https://user-images.githubusercontent.com/591146/103860310-bc1c2680-50bb-11eb-9af5-a3a99c3ba8e7.png)

Please do not make any effort here. We may not agree to a change.

**Comment by Turbocube644** [comment]
I checked the option and it is set to Automatic.
I tested the template with evaluateFormulas set to true and set to false, both did not update it.
When I have some spare time, I will look into providing a template where it doesn't work in order to check with you.

**Comment by Turbocube644** [comment]
Here is a simple template + code snipped where it does not work
(tested again with evaluateFormulas true and false)

```
public class App 
{
    public static void main( String[] args )
    {
        List<Payment> payments = new ArrayList<>(2);
        payments.add(new Payment(new Date(2019 - 1900, 1, 2), 2.0));
        payments.add(new Payment(new Date(2020 - 1900, 1, 9), 4.0));
        Booking one = new Booking("Test", "user", new Date(1999 - 1900, 11, 15), "test@test", payments);
        payments = new ArrayList<>(3);
        payments.add(new Payment(new Date(2019 - 1900, 3, 1), 10.0));
        payments.add(new Payment(new Date(2020 - 1900, 4, 2), 12.0));
        payments.add(new Payment(new Date(2021 - 1900, 5, 3), 50.0));
        Booking two = new Booking("User2", "Test", new Date(2000 - 1900, 11, 15), "testing@all", payments);
        List<Booking> bookings = new ArrayList<>(2);
        bookings.add(one);
        bookings.add(two);
        try(InputStream is = new FileInputStream("src/main/resources/template.xlsx")) {
            try (OutputStream os = new FileOutputStream("export.xlsx")) {
                Context context = new Context();
                context.putVar("name", "Testname");
                context.putVar("bookings", bookings);
                JxlsHelper.getInstance().setEvaluateFormulas(false).processTemplate(is, os, context);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static class Booking {
        private String firstName;
        private String lastName;
        private Date birthday;
        private String email;
        private List<Payment> payments;

        public Booking(String firstName, String lastName, Date birthday, String email, List<Payment> payments) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.birthday = birthday;
            this.email = email;
            this.payments = payments;
        }

        public String getFirstName() {
            return firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public Date getBirthday() {
            return birthday;
        }

        public String getEmail() {
            return email;
        }

        public List<Payment> getPayments() {
            return payments;
        }
    }

    public static class Payment {
        private Date date;
        private Double amount;

        public Payment(Date date, Double amount) {
            this.date = date;
            this.amount = amount;
        }

        public Date getDate() {
            return date;
        }

        public Double getAmount() {
            return amount;
        }
    }
}
```
[template.xlsx](https://github.com/jxlsteam/jxls/files/5789496/template.xlsx)

**Comment by SoltauFintel** [comment]
You're a funny guy. Tell us that evaluateFormulas doesn't work, but uses a super complicated formula in the template. JxlsHelper Javadoc: "Please be aware that e.g. POI supports only a subset of Excel formulas." -> WONTFIX

**Comment by Turbocube644** [comment]
Thanks for pointing out my funniness but I think you don't get my point.
Your documentation says, that Excel should update the cells if evaluateFormulas is set to false. So I do not blame Jxls for not handling the formulas. But your documentation states, that Excel should update the formulas, if "evaluateFormulas" is set to false (which it does not). Correct me if I'm wrong, but Excel should be able to handle these "super complicated formula", right?

The point being is, that evaluateFormulas = false does not (or at least not always) results in an evaluation when opening the Excel. Maybe I should been more clear about that...

**Comment by SoltauFintel** [comment]
You have 2 possibilities:
a) use your forceFormulaRecalculation stuff. Tip: decorator pattern with TransformerDelegator.beforeWrite()
b) handle the complicated formula in your Java code

I will change the Javadoc. (Who cares about documentation if you can read code...)

**Comment by SoltauFintel** [comment]
> Correct me if I'm wrong, but Excel should be able to handle these "super complicated formula", right?

I can't guarantee that. I'm not Microsoft.

**Comment by Turbocube644** [comment]
I guess Microsoft is pretty good with their stuff and the formula isn't that complicated. (But the reference a bit unclear).
Anyway the TransformerDelegator of course does work.

How about adding the `forceFormulaRecalculation` option to JxlsHelper with default `false`? It's a non breaking change and would perhaps also help others with complicated formulas.
I can also provide the code if you do not want to spend your time on it.

**Comment by SoltauFintel** [comment]
I did some research. See #87. You can do it.

**Comment by SoltauFintel** [comment]
@Turbocube644  - no reaction in #87  ??
