### ISSUE TITLE
Formula recalculation

### ISSUE THREAD

**Issue by SoltauFintel** [jxlsteam/jxls#87]
If an MS Excel user wants formulas to be calculated automatically, he must activate the calculation options to auto. (XLSX internal: workbook>calcPr>calcMode=auto)

![image](https://user-images.githubusercontent.com/591146/105759174-6ddaa480-5f50-11eb-8591-faf5a0ee335d.png)
(German Excel 365)

JxlsHelper.setEvaluateFormulas(true) causes in JXLS that all formulas are recalculated before saving. This only works as far as Apache POI supports it. This is useful if the created file is to be processed automatically (without Excel).

We suggest a new JxlsHelper- and Transformer- property **fullFormulaRecalculationOnOpening** with default value false. If set to true it will call POI XSSFWorkbook.setForceFormulaRecalculation(true) (see javadoc!) which activates the XLSX option fullCalcOnLoad (and possibly also calcMode=auto). When opening the created file in Excel a full recalculation will take place. This will change the file. The fullCalcOnLoad flag will be removed. So this works only once.

I want to mention that there is also CTCalcPr.setForceFullCalc() which I have not tested.

This ticket is the successor to #82.

**Comment by Turbocube644** [comment]
I intend to work on it, but unfortunately didn't find the time in the past weeks.
Do you already have a vague date for the next release?
(I couldn't answert to #82 as it is closed)

**Comment by SoltauFintel** [comment]
ok.
There is no due date for this ticket. ;-)
Release date: I don't know. Releasing depends on @leonate 
And I have to process 2 PR.

**Comment by Turbocube644** [comment]
Excel uses the OpenXML Format. The best Documentation I could find for this is: https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_calcPr_topic_ID0EWJ63.html

If I understand it correct, `CTCalcPr.setForceFullCalc` should do the same as `setFullCalcOnLoad(true)` together with `setCalcMode(STCalcMode.AUTO)`. This is exactly what Apache POI does on `workbook.setForceFormulaRecalculation(true)`
