### ISSUE TITLE
The template underline will be cannel?

### ISSUE THREAD

**Issue by neal-armstrong** [jxlsteam/jxls#89]
![image](https://user-images.githubusercontent.com/20726602/106581017-5b2e2400-657d-11eb-8ddd-349c0b1e262e.png)
![image](https://user-images.githubusercontent.com/20726602/106581096-6f722100-657d-11eb-866a-5da7f8fec920.png)

export excel the underline is missing.

**Comment by neal-armstrong** [comment]
soft dev:
![image](https://user-images.githubusercontent.com/20726602/106581298-ad6f4500-657d-11eb-990e-1f398561af7e.png)

**Comment by SoltauFintel** [comment]
I suggest that you recreate an almost empty Excel file with MS Excel. So then test whether underline works.

Is this a normal underline or a more special feature (e.g. form field)?

**Comment by neal-armstrong** [comment]
![image](https://user-images.githubusercontent.com/20726602/106691279-3209a400-660e-11eb-8120-2bb0c145e24a.png)
Amazing! it's work, Thanks, But why?
Does it contain special charcter?

**Comment by neal-armstrong** [comment]
by the way , How can use checkbox in the excel by code? using special character?

**Comment by SoltauFintel** [comment]
I don't know. That's a Excel specific question, not a JXLS question.

I guess the problem is solved. -> closed
