### ISSUE TITLE
Escaping single quotes in jxls2 query, is it possible?

### ISSUE THREAD

**Issue by eduardo-rs** [jxlsteam/jxls#90]
Hi,

in jxls1 we have the following: http://jxls.sourceforge.net/1.x/reference/sqlreporting.html

 <jx:forEach items="${rm.exec("SELECT d.name depname, e.name empname, age, payment, bonus, birthDate FROM employee e, department d WHERE d.id = e.depid AND birthDate > '1975-01-01' ")}" var="employee">

**"Also you can see how it is possible to use single quotes inside SQL query if needed."**

so you can use single quotes ' inside the rm.exec. 

I am trying to do the same in JXLS2, but it does not work: 
jx:each(items="jdbc.query("SELECT d.name depname, e.name empname, age, payment, bonus, birthDate FROM employee e, department d WHERE d.id = e.depid AND birthDate > '1975-01-01'")" var="row" lastCell="I2")

Am I missing something or is this not supported in JXLS2 ?

Regards,
Eduardo

**Comment by SoltauFintel** [comment]
Have you tried double single quotes?

I wrote µ instead of single quote.

SQL:

SELECT * FROM dual WHERE µ1µ=µ1µ

in items field:

" SELECT * FROM dual WHERE µµ1µµ=µµ1µµ "

**Comment by eduardo-rs** [comment]
This does not work in my case, I tried many combinations but I always get empty results back. So is this not supported in jxls2 ?

**Comment by SoltauFintel** [comment]
It's already possible to use a single quote in a SQL. Escape it with a leading backslash.

I updated SqlDemo.

**Comment by SoltauFintel** [comment]
@eduardo-rs 

I suggest you think about an sql attribute for jx:each to make SQL database easier to use. If you like, please write a concept and start a new ticket. How is that supposed to work with "jdbc.query" or the like? How is that supposed to work with arguments and JEXL variables?
