### ISSUE TITLE
Nested SQL queries EvaluationException

### ISSUE THREAD

**Issue by anadirov** [jxlsteam/jxls#92]
Expression: ```jx:each(items="jdbc.query('select first_name, to_char(birth_date, 'YYYY-MM-DD HH24:MI:SS') as birth_date from person')" var="person" lastCell="E3")```
Causes: ```org.jxls.expression.JexlExpressionEvaluator.evaluate@1:11 parsing error in '('```

![image](https://user-images.githubusercontent.com/79195758/108186949-294dbd80-7138-11eb-90f9-6530b14d9b3d.png)

**Comment by SoltauFintel** [comment]
see #90

**Comment by SoltauFintel** [comment]
Please use `jx:each(items="jdbc.query('select first_name, to_char(birth_date, \'YYYY-MM-DD HH24:MI:SS\') as birth_date from person')" var="person" lastCell="E3")`
